### DISCUSSION TITLE
Build-deploy asks for update to Node.js 20, even when using correct actions

### DISCUSSION THREAD

**Discussion by arahmitz** [peaceiris/actions-gh-pages#1071] [Q&A]
Hey, I am building with a query like this:
```
name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
```

So I basically changed `actions/checkout@v3` to `actions/checkout@v4`, as I understand that setup and deploy functions should remain the same - is there anything else I should update using Hugo?

It generally yells that both actions-hugo and actions-gh-pages are still using Node.js 16, even though I saw that there was a bump to Node.js 20 on these repos.
