### DISCUSSION TITLE
HTML does not show tikz figures

### DISCUSSION THREAD

**Discussion by lorenzoFabbri** [peaceiris/actions-gh-pages#1084] [Q&A]
I am compiling a `tex` file to PDF and HTML with GitHub Actions. The complete repository can be found [here](https://github.com/lorenzoFabbri/causal-effects-id). The PDF looks good, but the [HTML](https://lorenzofabbri.github.io/causal-effects-id/) does not. One problem is that the `tikz` figures are not displayed at all, there is only the caption. A second, perhaps minor, issue is that the equations are not really looking that good: they are not malformatted, but they do not look as good as in the PDF. I am new to using Actions and `actions-gh-pages`.

I copy the `yml` file here:

```
name: Build and Deploy LaTeX document
permissions: write-all

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
      - uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -u -f html5+dvisvgm_hashes -d out main.tex"
      - run: |
          cd out
          sudo mv main.html index.html
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: main-pdf
          path: main.pdf
      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: Current
          files: main.pdf
      - uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./out
```
