### DISCUSSION TITLE
Branch gh-pages did not created automatically

### DISCUSSION THREAD

**Discussion by aceton41k** [peaceiris/actions-gh-pages#1103] [Q&A]
I'm trying to deploy my allure report but the branch did not created by action
Log part with an error:

![image](https://github.com/user-attachments/assets/2fe9ae9b-2c76-4592-8dd7-a116c25b0328)
![image](https://github.com/user-attachments/assets/eea3fe1c-e0fd-4be8-aac3-d56701d6466f)

Part of yml file:
```
- name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages
          allure_results: './tests/build/allure-results'
          allure_report: './tests/build/allure-report'

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
```

.yml file and full logs attached
[gradle-ci.yml.txt](https://github.com/user-attachments/files/17002838/gradle-ci.yml.txt)
[job-logs.txt](https://github.com/user-attachments/files/17002852/job-logs.txt)

Thanks in advance for any help
