### DISCUSSION TITLE
Publish Jekyll locally generated main branch _site subdir to gh-pages branch for GitHub Pages User site?

### DISCUSSION THREAD

**Discussion by BillHertzing** [peaceiris/actions-gh-pages#596] [Q&A] [answered]
I'd like to use GitHub Pages to host my user Blog site. I'd like to have Jekyll build my site locally (to `./_site`) on my Windows 10 PC with non-whitelisted plugins and non-whitelisted themes, and I then commit everything to the `main` branch. If I add a tag like ` releases/\d+\.\d+\.\d+ ` to a commit, I'd like `actions-gh-pages` to publish the contents of `main`'s _`site` subdirectory to my GitHub repository's `gh-pages` branch. I've removed `_site` from the `.gitignore`, so it gets tracked and pushed to GitHub on every sync. The workflow `.yml` specifies a trigger that (should) only fire if the commit includes a tag that matches the Semantic Version release tag

```yml
on:
  # Triggers the workflow on push requests to the main branch if the commit includes a tag that matches the Semantic Version release tag
  push:
    # tags: [ releases/\d+\.\d+\.\d+ ]
    branches: [ main ]
  # This line allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```
Although I have not released any release tags yet, I  have that tags conditional commented out, to run the action and deploy on every commit until I get the Deploy action working.

The deploy step looks like this:

```yml
- name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site # the action will deploy the <repository root>/_site contents to the (default) gh-pages branch, root directory
```

But it is not working. Is it possible to use `actions-gh-pages` to publish `_site` to `gh-pages` branch for a GitHub Pages user site?  I've tried a `publish_dir` of `./_site`, `./`, `.`, and even `../_site`, none of which seem to work.  With `./_site`, I get this error: ` cp: no such file or directory: /home/runner/work/Bill.Hertzing.github.io/Bill.Hertzing.github.io/_site/.*`

I'm in the very early stage of building the site. It's public, at [Bill.Hertzing.github.io](https://github.com/BillHertzing/Bill.Hertzing.github.io). I'd certainly appreciate it if you could let me know what's wrong with my Deploy step.  There is also the first technical post with lots of details, and at it's end you can see the step I'm stuck on

Thanks for your work on creating this action!
