### DISCUSSION TITLE
How to run the deploy only on main branch?

### DISCUSSION THREAD

**Discussion by simonppg** [peaceiris/actions-gh-pages#630] [Q&A] [answered]
Is there a way to only run the deploy on main branch? I have this configuration but it also runs when a new pull request is created, could somebody point me out to the right direction?

```
name: cd

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```

I don't know if this is relevant but I'm using nuxtjs static pages.
