### DISCUSSION TITLE
Hugo Site on Master Branch

### DISCUSSION THREAD

**Discussion by sirinath** [peaceiris/actions-gh-pages#642] [Q&A] [answered]
How can the configuration be changed if the site is on the master branch?

What would be the repos structure with `md`, `adoc` files and output?

Is there any specifics in installing action for Hugo? Should both actions be installed?

**Comment by peaceiris** [comment, marked as answer]
## If your default branch is master (main) and you are using the `gh-pages` as the GitHub Pages branch

Just follow the README.

## If you are using master branch as the **GitHub Pages branch**

If you are a senior GitHub user, you know that the GitHub Pages branch was limited to `gh-pages` or `master` only in the old days. [Today, we can select any branch as the GitHub Pages branch.](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

- Project repository: ~~Only `gh-pages`.~~ Today, any branch.
- User repository (e.g. `peaceiris/peaceiris.github.io`): ~~Only `master`.~~ Today, any branch.

![Today, we can select any branch as the GitHub Pages branch.](https://user-images.githubusercontent.com/30958501/128742992-16187721-dc5b-4b91-bb6a-8b0ac8012d2a.png)

For more details and the latest spec, see the official documentation: [GitHub Pages Documentation - GitHub Docs](https://docs.github.com/en/pages)

Here is an example workflow for the old GitHub users.

Usecase:

- `source` branch has a Hugo project (Markdown files, Hugo templates, etc.)
- `master` branch is the GitHub Pages branch including build assets (HTML, CSS, JavaScript, etc.)

We can select the GitHub Pages branch with the `publish_branch` input. (default is `gh-pages`).

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - source  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
```

For more options and use cases, read [the latest README.md](https://github.com/peaceiris/actions-gh-pages#readme)
