### DISCUSSION TITLE
Deploy to GitHub Pages Auto Bot

### DISCUSSION THREAD

**Discussion by joesan** [peaceiris/actions-gh-pages#688] [Q&A] [answered]
I have been using this GitHub action to deploy the changes to my GitHub pages:

 
```
 deploy:
    runs-on: ubuntu-20.04
    needs: linkChecker
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) tt + another test
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
```
It was fine until 3 days ago where I keep seeing after every single run an additional pipeline step as [seen from this screenshot](https://aws1.discourse-cdn.com/standard10/uploads/gohugo/original/2X/1/12bbb075c80c01deb8cfb5c592a33201fee2186b.png):

It can be seen that it is a Bot that is getting run after every single time. I would like to avoid this. Any ideas what is happening? I did not configure thic Bot in my GitHub account.

**Comment by peaceiris** [comment]
That is another workflow that was an internal workflow of GitHub.

For more details: [GitHub Pages: using GitHub Actions for builds and deployments for public repositories | GitHub Changelog](https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/)

See also https://github.com/peaceiris/actions-gh-pages/discussions/684#discussioncomment-1843213

**Comment by joesan** [comment]
How can I then disable it? Every single run causes or triggers this bot and it is duplicating the buld and deployment.

**Comment by joesan** [comment]
I do an additional step to check for HTTP links in my markdown files and I list all the content that is in draft status before I run the peaceiris action to deploy to gh-pages. So would this GitHub bot now mean that I can disable peaceiris action?

**Comment by peaceiris** [comment, marked as answer]
GitHub has migrated their internal pipeline of GitHub Pages deployment to the new workflow. Disabling the new workflow means "Disable GitHub Pages".

Thanks to the new workflow, we can see the log message of the internal pipeline of GitHub Pages deployment.

We don't have to change our workflow for the new one.

**Comment by peaceiris** [comment]
See also https://github.com/peaceiris/actions-gh-pages/discussions/684#discussioncomment-1843213

**Comment by joesan** [comment]
I don't know if you understood my question. My question was, should I remove this from my main.yml?

  ```
deploy:
    runs-on: ubuntu-20.04
    needs: linkChecker
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) tt + another test
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
```

GitHub is doing this automatically with the bot so what is the purpose of this now?
