### DISCUSSION TITLE
gh-pages branch not created?

### DISCUSSION THREAD

**Discussion by Aryaman73** [peaceiris/actions-gh-pages#691] [Q&A] [answered]
I was trying to follow these steps: https://gohugo.io/hosting-and-deployment/hosting-on-github/

I copied the workflow in, and it seems to be correctly trigger the GitHub action. However, the steps above says:

> By default, the GitHub action pushes the generated content to the gh-pages branch. This means GitHub has to serve your gh-pages branch as a GitHub Pages branch.

How does this work? I don't have a gh-pages branch, and it hasn't created one for me. I don't know where/if the action is creating my static files. My website is currently trying to deploy off of main, which obviously won't work. 

Here is my repository: https://github.com/Aryaman73/aryaman73.github.io

Does anyone here know what I'm missing?

Thanks!

EDIT: Adding `publish_branch: gh-pages` explicitly to the gh-pages.yml also doesn't seem to work.

**Comment by peaceiris** [comment, marked as answer]
Here is your workflow.

```yaml
on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:
...
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

You are using `master` branch as your source branch. Change the filter of the Deploy step.

```diff
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
-        if: github.ref == 'refs/heads/main'
+        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
