### DISCUSSION TITLE
How to set HUGO_ENV deploying Hugo site

### DISCUSSION THREAD

**Discussion by giopad** [peaceiris/actions-gh-pages#696] [Q&A] [answered]
I would like to set HUGO_ENV=production deploying my site on Github to change .
Is it possible to insert  - HUGO_ENV=production hugo - in the worklflow?
Can you tell me how to?
Many thanks.
giopad

**Comment by peaceiris** [comment, marked as answer]
docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env

```yaml
      - name: Build
        env:
          HUGO_ENV: production
        run: hugo --minify
```
