### DISCUSSION TITLE
Confused how to use enable_jekyll

### DISCUSSION THREAD

**Discussion by redonkulus** [peaceiris/actions-gh-pages#769] [Q&A] [answered]
I'm using GitHub Pages for https://github.com/acss-io/atomizer. Right now, GH Pages is setup on the `master` branch and `./docs` directory. However, I want to change this to `gh-pages` branch and `./` directory.

I'm trying to use this action with the following settings:

```yaml
            - name: Deploy
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  enable_jekyll: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_site
```

When the job runs, the jekyll files are not built and nothing is copied to the gh-pages page. I tried to [fix from the readme](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token) for first commit by changing the settings and running the build again but it still [did not publish anything](https://github.com/acss-io/atomizer/tree/gh-pages).

It was my understanding that setting `enable_jekyll: true` should trigger the Jekyll build but it looks like that is not the case as my `./docs/_site` is not being built:

![Screen Shot 2022-07-19 at 3 40 45 PM](https://user-images.githubusercontent.com/193272/179860411-6ab4392e-bba5-418a-9d4f-f650ae8bfe6f.jpg)

Source: https://github.com/acss-io/atomizer/runs/7418634700?check_suite_focus=true

Are my assumptions incorrect or am I doing something wrong?
