### DISCUSSION TITLE
Inform in coderefinery tutorial about branch customization

### DISCUSSION THREAD

**Discussion by maciejskorski** [peaceiris/actions-gh-pages#773] [Ideas]
First, thanks a lot for this useful workflow!

A comment on improving the doc: when following the [tutorial exercise](https://coderefinery.github.io/documentation/gh_workflow/#exercise-deploy-sphinx-documentation-to-github-pages) on deploying Shinx docs to GitHub Pages you are encouraged to copy-and-paste 
```
name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
```

In addition to the encouraging sentence `You don’t need to understand all of the above` 😆   the beginners would welcome a word of caution: **adjust branch names to your use-case** (the common e.g. master/dev GitFlow). Solves for future reocurring issues like #691.
Thanks!
