### DISCUSSION TITLE
Moving .html file to ./public directory

### DISCUSSION THREAD

**Discussion by Tsaftaridis** [peaceiris/actions-gh-pages#886] [Q&A] [answered]
Hello! I am trying to build a narrative game with twine (a tool for creating HTML, CSS and Javascript narrative games) and the relevant CLI tool, called tweego, with automated deployment using github actions. 

As far as I understand, the index.html file that is created needs to be in a directory called public, from which it is by default published in the next step of the workflow. However, I cannot move it into that directory or create it there. I get this error message: 

```
Run go get github.com/tmedwards/tweego
  go get github.com/tmedwards/tweego
  export PATH=$PATH:$(go env GOPATH)/bin
  tweego testcase.twee -o public/index.html
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.15/x64
error: open public/index.html: no such file or directory
Error: Process completed with exit code 1.
```
My workflow contains this relevant piece: 

```
- name: build game
        run: | 
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego testcase.twee -o public/index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
```

If I change "public/index.html" to "index.html" it runs without error, but the github pages deployment is empty. 

Even more background: I used [this tutorial](https://dev.to/lazerwalker/a-modern-developer-s-workflow-for-twine-4imp), and changed ./dir to ./public, from what I gathered from the documentation. 
Is this anything obvious? I will keep trying and post with anything new.
