### ISSUE TITLE
support: can an application token be used to deploy?

### ISSUE THREAD

**Issue by btrautmann** [peaceiris/actions-gh-pages#1054]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

The README clearly outlines the ability to use `GITHUB_TOKEN`, a deploy key, or SSH key for deploying. I'm wondering if I could use a short-lived application token (installed/configured for the repo) to deploy? I've tried a few different approaches but none seem to work and I can't find any questions asking the same.

### Relevant links

```markdown
Our repository is private so can't be linked to.
```

### Relevant log output

One of two errors happens depending on configuration:

1. Action failed with "The process '/usr/bin/git' failed with exit code 1"
2. Action failed with "The generated GITHUB_TOKEN (github_token) does not support to push to an external repository. Use deploy_key or personal_token."

### Additional context.

We're using the following to get the app token:

```yaml
      - name: Get application token
        id: get_token
        uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc #v2.0.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
```
