### ISSUE TITLE
support: Actions/cache for Hugo modules with Hugo v0.127.0

### ISSUE THREAD

**Issue by Zer0xxxx** [peaceiris/actions-gh-pages#1081]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Hello!

I'm running on Hugo v0.127.0
And I'm also using a Hugo module (Blowfish).

From the docs of this GitHub Action:
* [⭐️ Caching Hugo Modules](https://github.com/marketplace/actions/hugo-setup#%EF%B8%8F-caching-hugo-modules)

```
    path: /home/runner/.cache/hugo_cache    # <-- with hugo version v0.116.0 and above
    # path: /tmp/hugo_cache                 # <-- with hugo version < v0.116.0
```

But, I've checked both folders in my CI, and don't find any of them.
I've even fired a ls -R /home/runner/
And a ls -R .

And I don't find any "hugo_cache"

It's weird, since I'm not using the --gc flag at the build of my Hugo website.
I did everything exactly as it is documented.

Also, this is quite annoying, because the download of the module is likely 78% of the duration of my CI/CD...

> hugo: collected modules in 17347 ms

Also:

> ls: cannot access '/home/runner/.cache/hugo_cache': No such file or directory
> ls: cannot access '/home/runner/.cache': No such file or directory

And `ls /tmp` gives:

```
clr-debug-pipe-1618-22959-in
clr-debug-pipe-1618-22959-out
clr-debug-pipe-1635-23181-in
clr-debug-pipe-1635-23181-out
clr-debug-pipe-592-844-in
clr-debug-pipe-592-844-out
dotnet-diagnostic-1618-22959-socket
dotnet-diagnostic-1635-23181-socket
dotnet-diagnostic-592-844-socket
hugo_cache_runner
snap-private-tmp
systemd-private-400d24fb912f435db1794cbdf1e0ff7c-chrony.service-PXMl8E
systemd-private-400d24fb912f435db1794cbdf1e0ff7c-haveged.service-QZT8c2
systemd-private-400d24fb912f435db1794cbdf1e0ff7c-systemd-logind.service-E0KxuY
systemd-private-400d24fb912f435db1794cbdf1e0ff7c-systemd-resolved.service-ZNa6Mx
www-data-temp-aspnet-0
```

There is a **hugo_cache_runner** here, but it seems to be pointless in this context...

Any clue?

### Relevant links

> Public repository: https://github.com/chill-utility/chill-utility.github.io
> YAML config: https://github.com/chill-utility/chill-utility.github.io/blob/main/.github/workflows/deploy.yml
> Hugo's forum topic: https://discourse.gohugo.io/t/how-to-cache-hugo-modules-in-a-github-action/50334

**Comment by Zer0xxxx** [comment]
Oh, okay, finally found the right way to do it.
Just defining the env variable and rely on it seems to be perfectly safe.

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.127.0
      HUGO_CACHEDIR: /tmp/hugo_cache
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
