### ISSUE TITLE
support: Error: Unable to resolve actions. Cannot access repositories 'peaceiris/actions-gh-pages'

### ISSUE THREAD

**Issue by ashokvaddevalli** [peaceiris/actions-gh-pages#1083]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

We are facing issues using this action on Github Enterprise. 

Error: Unable to resolve actions. Cannot access repositories 'peaceiris/actions-gh-pages'. Enable access using Settings in the Action repository. See https://docs.github.com/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-an-internal-repository for more information.

### Relevant links

```markdown
Public repository:
YAML config:
YAML workflow:
 - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure report action
        uses: simple-elf/allure-report-action@58e6590adf6d8f196a0d771bf8a00e6921086a62
        if: always()
        with:
          allure_results: allure-report
          allure_history: allure-history
          keep_reports: 10
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GHE_TOKEN }}
          publish_branch: gh-pages
           publish_dir: allure-history
```

### Relevant log output

Getting action download info
Error: Unable to resolve actions. Cannot access repositories 'peaceiris/actions-gh-pages'. Enable access using Settings in the Action repository. See https://docs.github.com/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-an-internal-repository for more information.

**Comment by peaceiris** [comment]
Please check your setting.

cf.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run

![スクリーンショット 2024-06-24 午前10 35 34](https://github.com/peaceiris/actions-gh-pages/assets/30958501/c42b863c-2527-4c49-8774-e4f9c94cab3f)

**Comment by ashokvaddevalli** [comment]
Hi,
We are using GitHub Enterprise, and we can't enable all actions due to security reasons. We are enabling the required actions as per request. We are enabled this action peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e but we are facing the issue. Any dependent actions for this action? 

![image](https://github.com/peaceiris/actions-gh-pages/assets/3022813/eded6f1d-0126-4ef6-8e0a-fbd72c84e77a)

**Comment by ashokvaddevalli** [comment]
I tried using commit has only, but the issue is the same.

- name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        if: always()
        with:
          github_token: ${{ secrets.GHE_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

**Comment by peaceiris** [comment]
Ah, it seems that we cannot override a policy managed by the enterprise. Could you ask the enterprise owners to add this action to the allow list using the commit hash?

https://docs.github.com/en/enterprise-server@3.12/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-to-run

> [!NOTE]
> You might not be able to manage these settings if your organization has an overriding policy or is managed by an enterprise that has overriding policy. For more information, see "[Disabling or limiting GitHub Actions for your organization](https://docs.github.com/en/enterprise-server@3.12/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization)" or "[Enforcing policies for GitHub Actions in your enterprise](https://docs.github.com/en/enterprise-server@3.12/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise)."

**Comment by ashokvaddevalli** [comment]
Hi,
This action is already enabled after my request but i am facing this issue.
"peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e"

**Comment by peaceiris** [comment]
Oh, sorry. I have no more idea about this...

Today, the official custom GitHub Action to deploy GitHub Pages is available. We can try it.

- https://github.com/actions/deploy-pages
- https://docs.github.com/en/enterprise-server@3.12/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages

**Comment by ashokvaddevalli** [comment]
Hi,
Using deploy-pages action, i have not seen publish_branch and publish_dir options.

 - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

**Comment by peaceiris** [comment]
Also, we need the [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact) to upload our `publish_dir`.

Here is an example workflow (not tested).

```yaml
name: Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: build_something

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "publish_dir"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
