### ISSUE TITLE
support: self-hosted runner

### ISSUE THREAD

**Issue by bryantvolk** [peaceiris/actions-gh-pages#1085]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

is it possible to use a self hosted runner for the `pages build and deployment` workflow that this triggers?

here's my job snippet

```
jobs:
  storybook:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Storybook Staging
        if: github.ref != 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ./sb/${{ steps.branch-name.outputs.short_ref }}
```

i skipped all the fun stuff.

this results in my `storybook` job running on the runner `self-hosted` but the triggered `pages build and deployment` is running on the github hosted `ubuntu-lastest` or whatever. 

this is an issue because the runner is timing out due to upload size/artifact count (presumably)

### Relevant links

```markdown
Public repository: not public
YAML config: see above
YAML workflow: see above
```

### Relevant log output

the workflow has the annotation

`The hosted runner lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`
