### ISSUE TITLE
Use docker image from GitHub Package Registry

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#11]
2019-09-02: We cannot pull docker images from GitHub Package Registry.
cf. [Workflow syntax for GitHub Actions - GitHub Help](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses)

I asked about this at [Use docker images from GitHub Package Registry - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Use-docker-images-from-GitHub-Package-Registry/m-p/30407)

`.github/workflows/docker-image-ci.yml`

```yaml
on:
  release:
    types: [published, created]

    - name: push latest image
      env:
        DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/action:latest
        PKG_GITHUB_TOKEN: ${{ secrets.PKG_GITHUB_TOKEN }}
      run: |
        echo ${PKG_GITHUB_TOKEN} | docker login docker.pkg.github.com -u peaceiris --password-stdin
        docker push ${DOCKER_IMAGE} &&
        docker logout
```
