### ISSUE TITLE
support:  unable to access 'https://github.com/saigkill/SaschasToolbox.git/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by saigkill** [peaceiris/actions-gh-pages#1102]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I defined a Job:

```yaml
doxygen:    
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Setup Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:          
         doxyfile-path: 'doxygen/Doxyfile'      
    - name: Deploy Doxygen documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/html
````

While executing the actions-gh-pages job i'm getting:

```txt
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to saigkill/SaschasToolbox.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/saigkill/SaschasToolbox.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code [128](https://github.com/saigkill/SaschasToolbox/actions/runs/10745865186/job/29805745309#step:5:134)"
```

I used GITHUB_TOKEN as proposed in the documentation.

### Relevant links

```markdown
Public repository: https://github.com/saigkill/SaschasToolbox
YAML config:
YAML workflow: https://github.com/saigkill/SaschasToolbox/blob/master/.github/workflows/dotnet.yml
```

### Relevant log output

Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to saigkill/SaschasToolbox.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/saigkill/SaschasToolbox.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code [128]
