### ISSUE TITLE
feat: Add disable_nojekyll and cname options

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#112]
> Yeah, I had exactly the same behavior in the Settings page.
>
> Another problem I had additionally was that adding a empty commit after fixing the settings didn't seemed sufficient. It triggered the Gihub Actions workflow but not the Github Pages workflow. It seemed necessary to really alter the content of the `gh-pages` branch in order to publish. It may be useful that say that I'm using Parcel, which generates exactly the same content byte-per-byte given the same source files to optimize caches, and that I use a `.nojekyll` file to avoid problems.
>
> I think Github has some mechanism to avoid publishing if the content of `gh-pages` didn't changed, at least when using the `.nojekyll` file.
>
> By the way, this is completely unrelated but it could be a good idea to add that `.nojekyll` file by default in your action. 99% of the users will need it, will probably not read the whole documentation so they won't know, and will inevitably encounter a hard to debug problem sooner or later. (I'm convinced all serious users of Github Pages already lost at least one hour of their time because of that damn file like I did ^^ )

_Originally posted by @nicolas-van in https://github.com/peaceiris/actions-gh-pages/issues/9#issuecomment-588129844_

**Comment by dhimmel** [comment]
I am guessing this will be similar to the `--no-jekyll` option of [ghp-import](https://github.com/davisp/ghp-import). The javascript [`gh-pages`](https://github.com/tschaub/gh-pages) utility doesn't have this option, but does have a `--dotfiles` option that must be specified to copy over files starting with `.`.

Personally I like the `ghp-import` design where adding the `.nojekyll` file is an opt-in option.

**Comment by peaceiris** [comment]
Yes. Some static site generators like Hugo and Gatsby.js support to adding the `.nojekyll` file as a static asset. To avoid conflicting with that feature, supporting the `add_nojekyll` option may be better for us.

**Comment by dhimmel** [comment]
You might want to also consider an option to write a `CNAME` file for configuring [custom domains](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain). For this option, the user would want to pass a string that gets written to the `CNAME` file.

**Comment by peaceiris** [comment]
As I said at #25, the same may be said of other files (BingSiteAuth.xml, robots.txt, and so on). I think that it is better to manage those files as files.

What is the difference between (BingSiteAuth.xml, robots.txt) and (CNAME, .nojekyll)? Those all look just files. I do not know whether we should provide the `add_nojekyll` like feature, or not.

What do you think about this? @dhimmel @nicolas-van

**Comment by nicolas-van** [comment]
Personally I think that the fact that some static website generators support adding a `.nojekyll` is kind of a bad design from them (their job should just be to generate HTML). On the other hand it should be the job of a tool designed specifically to upload to Github Pages. 

Also I think the Jekyll feature of Github as a whole should be considered completely deprecated since the availability of Github Actions. Why would you use a super specific feature when you can basically do whatever you want ? (Including triggering your own Jekyll build if you like that generator, but with the plugins you choose instead of a fixed set which has always been very limited.)

So my opinion regarding the `.nojekyll` file generation feature would be:

* To tolerate if the file already exists (generate it only if it doesn't exist, which means it will never crash)
* To be an opt-out (only for the 0,1% of users that would like to use Github's custom Jekyll generator for legacy reasons)

Regarding `CNAME`, now that we speak about it it doesn't seem like a bad idea to add an option to generate it through the custom action. I just think it could be cleaner to have something like that:

```
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    publish_dir: ./public
    cname: example.com
```

Thank like that:

```
- run: echo "example.com" > public/CNAME
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    publish_dir: ./public
```

Although I would say it doesn't seem very important, that's just personal taste.

**Comment by dhimmel** [comment]
> I think the Jekyll feature of Github as a whole should be considered completely deprecated since the availability of Github Actions.

amen

> To be an opt-out (only for the 0,1% of users that would like to use Github's custom Jekyll generator for legacy reasons)

While I agree the majority of users deploying to `gh-pages` probably want `.nojekyll`. However, I think this action has a lot of utility as a general purpose deploy-to-branch action. When deploying outputs to branches other than `gh-pages`, it could be confusing to users to have to add an option to prevent an extra file from being added.

**Comment by peaceiris** [comment]
Thanks all.

OK. I will add two options: `disable_nojekyll` and `cname`. Thanks to the opinions of you all, I got a clear reason to add those. I thought that we should keep this action's role which is just copying the assets until today, but the specific features of GitHub Pages seem to be necessary for us.

Why adding `.nojekyll` is default behavior?

> While I agree the majority of users deploying to `gh-pages` probably want `.nojekyll`. However, I think this action has a lot of utility as a general purpose deploy-to-branch action. When deploying outputs to branches other than `gh-pages`, it could be confusing to users to have to add an option to prevent an extra file from being added.

I agree with this, so I am going to define the behavior like the following:

- Add `.nojekyll` file by default for **only** the `master` and `gh-pages` branches. When the file exists already do nothing.
- When we set other branches to `publish_dir`, this action does not add `.nojekyll` file.

How about this spec?

**Comment by nicolas-van** [comment]
Seems good to me.

**Comment by dhimmel** [comment]
> How about this spec?

Smart!

**Comment by peaceiris** [comment]
I opened #119 and released `v3.3.0-0`. Test it!

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.3.0-0
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    # github_token: ${{ secrets.GITHUB_TOKEN }}
    # personal_token: ${{ secrets.PERSONAL_TOKEN }}
    # publish_branch: master
    # publish_dir: ./public
    disable_nojekyll: true
    cname: peaceiris.com
```
