### ISSUE TITLE
Unable to deploy static hugo page due to auth issue

### ISSUE THREAD

**Issue by hakusaro** [peaceiris/actions-gh-pages#13]
Hi! I just setup a new hugo site with the intent to publish to the `gh-pages` branch of the same repo in the root directory (i.e., `.`).

The workflow looks like this:

```yaml
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: peaceiris/actions-hugo@v0.58.0
        with:
          args: --gc --minify --cleanDestinationDir

      - name: deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: .
```

It fails on the deploy step with this:

```
/usr/bin/docker run --name b6eba6be5b8977615c40ca9a20a95bc21bdd74_f636c9 --label b6eba6 --workdir /github/workspace --rm -e GITHUB_TOKEN -e PUBLISH_BRANCH -e PUBLISH_DIR -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/p17/p17":"/github/workspace" b6eba6:be5b8977615c40ca9a20a95bc21bdd74
Reinitialized existing Git repository in /github/workspace/.git/
fatal: remote origin already exists.
Switched to a new branch 'gh-pages'
Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
[gh-pages 314b0a0] Automated deployment: Thu Sep  5 06:20:36 UTC 2019 466fd027c30da77da2cd2c1dfbf47912ce4c1f15
 4 files changed, 4 insertions(+)
 create mode 100644 public/categories/index.xml
 create mode 100644 public/index.xml
 create mode 100644 public/sitemap.xml
 create mode 100644 public/tags/index.xml
 fatal: could not read Username for 'https://github.com': No such device or address
##[error]Docker run failed with exit code 128
```

Any ideas on what I'm doing wrong?

**Comment by peaceiris** [comment]
Can I see your repo? public?

**Comment by hakusaro** [comment]
Soz, it's private. The gh-pages branch is just an orphan with an initial commit if that helps?

**Comment by peaceiris** [comment]
Ok. Sorry, I cannot find the cause of your problem.

#10 doesn't become a solution to the root of your problem, but it will work well. Please try to use #10 (use `ACTIONS_DEPLOY_KEY` instead `GITHUB_TOKEN`)

## (1) Setup deploy key

Generate your deploy key with the following command.

```sh
ssh-keygen -t rsa -b 4096 -C "your@email.com" -f gh-pages -N ""
# You will get 2 files:
#   gh-pages.pub (public key)
#   gh-pages     (private key)
```

Next, Go to **Repository Settings**

- Go to **Deploy Keys** and add your public key with the **Allow write access**
- Go to **Secrets** and add your private key as `ACTIONS_DEPLOY_KEY`

## (2) Edit your YAML file

```diff
- uses: peaceiris/actions-gh-pages@v1.1.0
+ uses: peaceiris/actions-gh-pages@release-v2.0.0
```

```diff
- GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+ ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
```

```diff
- PUBLISH_DIR: .
+ PUBLISH_DIR: ./public
```

**Comment by peaceiris** [comment]
`v2.0.0` is released.

```yaml
uses: peaceiris/actions-gh-pages@v2.0.0
```

**Comment by hakusaro** [comment]
Yep, that did the trick. I generated an SSH key, stored it on GitHub, and now everything is peachy.

My final deploy workflow looks something like this:

```yml
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_SSH_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public/
```

Thank you so much for helping out! ❤️
