### ISSUE TITLE
Add option to prevent step from running in forks

### ISSUE THREAD

**Issue by corollari** [peaceiris/actions-gh-pages#153]
**Is your feature request related to a problem? Please describe.**
When other users fork my repositories this action always fails on their forks because either they don't have the proper secret set up or the cname is already taken (by my upstream repo), this is slightly confusing and it requires me and the users to go to the build page for every build run in order to check if it's this action the one failing or if it's something else.

**Describe the solution you'd like**
It'd be great if we could toggle an option that would disable this specific action when it's being run in forks.

**Describe alternatives you've considered**
I can check the origin repository inside an if clause and only run the action if the origin is equal to the upstream name, but while this works it's a bit messy because it requires setting the repository id every time a workflow is set up.

Another alternative would be to just enable allow_failures, but then I wouldn't get alerted when the action fails to deploy the page correctly on the upstream repo.

Overall I don't know if this is something easily doable (the only solution I can think of for detecting if a repo is a fork involves querying github's api) or common enough to warrant it being included as an option.

In any case, I'm willing to implement a solution and create a PR if we manage to come up with an elegant solution to this problem.

**Comment by peaceiris** [comment]
There is a quick workaround like the following:

```yaml
- name: Deploy to GitHub Pages
  if: github.event.repository.fork == false
  uses: peaceiris/actions-gh-pages@v3
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    # publish_branch: gh-pages  # default
    publish_dir: ./path_to_dir
```

The deployment on a fork will skip but it is better and friendly for users to detect fork status by this action internally. We should consider whether this action is running on a fork, or not.

When we use the `deploy_key` or `personal_token` for deployment, those secret values are not provided to a fork. On the other hand, `GITHUB_TOKEN` is generated for each user so a fork user can use the `github_token` option.

```yaml
- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./path_to_dir
```

This setting works on a fork not only an original repository. Checking whether this action runs on a fork is needed for only `deploy_key` and `personal_token`.

Besides, disabling deployment on a fork by default is not good because some users are using this action on their fork for their deployment. (GitHub's fork feature is not for only pull requests.)

> Overall I don't know if this is something easily doable (the only solution I can think of for detecting if a repo is a fork involves querying github's api) or common enough to warrant it being included as an option.

Here is a simple example to get a repository metadata about fork status in action side.

```ts
import {context} from '@actions/github';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const isForkRepository: boolean = ((context.payload as any).repository.fork).toUpperCase() === 'TRUE';

core.info(`isForkRepository: ${isForkRepository}`);

if (isForkRepository) {
  core.info('[INFO] This action runs on a fork');
  // skip deployment
} else {
  // do usual stuff
}
```

> In any case, I'm willing to implement a solution and create a PR if we manage to come up with an elegant solution to this problem.

Thank you. I want more time to think about this specification.
