### ISSUE TITLE
option to commit .github files

### ISSUE THREAD

**Issue by pawsong** [peaceiris/actions-gh-pages#163]
Thank you for sharing this good project :)

**Is your feature request related to a problem? Please describe.**
In some use cases, we want to commit `.github` workflow files so that we can trigger actions on gh-pages branch.

**Describe the solution you'd like**
An option to determine if `.github` files to commit or not.

**Describe alternatives you've considered**
I made a commit to disable `.github` filtering, but I know this is a temporary workaround.

https://github.com/specup/actions-gh-pages/commit/9cb1a7cbf98862f00b2de481bf3911ec37973a2c

**Comment by peaceiris** [comment]
Adding a new option `exclude_files` may be a good solution. I will think about the details.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    exclude_files: |
      .env
      .nvmrc
```

**Comment by pawsong** [comment]
If `.git` should be always excluded, then how about excluding `.git` regardless of `exclude_files` option?

Then default value of `exclude_files` would be `.github`.

**Comment by pawsong** [comment]
Setting default value of `exclude_files` to `.git` or `.git .github`... both options looks reasonable to me.

**Comment by peaceiris** [comment]
Yes. We can exclude `.git` from a publish directory regardless of the `exclude_files` and define `.github` as a default value of the `exclude_files` option.

```yaml
inputs:
  exclude_files:
    description: 'Set files to exclude from a publish directory.'
    required: false
    default: '.github'
```

**Comment by peaceiris** [comment]
To mean that the option has files and directories, we should probably call it `exclude_assets`.

**Comment by pawsong** [comment]
How to exclude only files under `.git` directory? Possibly we can set `exclude_assets` to `false` or empty string (`''`).

**Comment by pawsong** [comment]
```yml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    exclude_files: false
```

Using `false` looks prettier for me.

**Comment by peaceiris** [comment]
Some users can have files that are named `false` or `true`, so I think empty is better.

**Comment by pawsong** [comment]
I agree with you. Using empty string is better.

**Comment by Legion2** [comment]
Why not excluding all files and directories starting with `.` by default. Because they are considered invisible.

**Comment by pawsong** [comment]
Excluding all dot files will be a breaking change for existing users.

**Comment by Legion2** [comment]
But else we have to discuss what is excluded by default. There are many dot files like the `.gitignore` you don't need to deploy to github pages. The simplest solution is to never deploy the root of the git repo, because it contains many configuration files.

**Comment by peaceiris** [comment]
For example, users who are using Static Site Generators (not GitHub Pages built-in Jekyll) need `.nojekyll` file.

@Legion2 See [this case](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-githubpersonal-website). Some users set `publish_dir: ./` and others set a git submodule to publish_dir. So we should not exclude all dotfiles by default.

**Comment by Legion2** [comment]
OK, but why should `.github` be excluded by default?

**Comment by pawsong** [comment]
@Legion2 The reason is described here

https://github.com/peaceiris/actions-gh-pages/issues/163#issuecomment-599983260

Some users use `publish_dir: ./` in there source code branch

**Comment by Legion2** [comment]
OK now I understand. When `.github` is not excluded, it will trigger some workflows on the github pages branch and that should not happen.

**Comment by corollari** [comment]
If you end up going with some variation of `exclude_assets` I'd propose adding a warning or something to the readme explaining why `.github` is excluded by default, as the reason is not trivial.

**Comment by peaceiris** [comment]
> If you end up going with some variation of `exclude_assets` I'd propose adding a warning or something to the readme explaining why `.github` is excluded by default, as the reason is not trivial.

Yes! We need a friendly description of the option.

It is probably useful to enable regular expression for the `exclude_assets` option. I will work on this issue on the weekend.

**Comment by Lucas-C** [comment]
I have a similar need : I'm using `publish_dir: ./` and I would like my `node_modules` directory to be commited on the `gh-pages` branch, despite this folder being in my `.gitignore` file.

Could an option be added that would perform a `git add -f` on some specific files before the commit ? -> https://github.com/peaceiris/actions-gh-pages/blob/master/src/main.ts#L55

(maybe I should open a separate issue ?)

**Comment by peaceiris** [comment]
@Lucas-C Could you open a new issue and tell me more details? I visited the https://github.com/covid19lejeu/covid-19-le-jeu/issues/14 but I did not understand it. I think your problem is not related to this issue.

**Comment by Lucas-C** [comment]
Ok

I think I found a workaround, by putting the files in a `public/` directory instead of using `./` directly : https://github.com/covid19lejeu/covid-19-le-jeu/pull/15/files

Hence I think I'll bother you with a bug report only if this tactic fails.

**Comment by peaceiris** [comment]
That's good!

Personally, I think projects that are using `publish_dir: ./` need to re-consider its directory structure. In addition, managing `node_modules` under Git control is a little strange, in this case, the webpack or Parcel is useful for assets bundling.

**Comment by radames** [comment]
Hi, is there any workaround to include `.github` ? My currently workflow only watches for changes on gh-pages branch, and you need `.github` inside that branch to trigger events there.

**Comment by peaceiris** [comment]
Currently, we have no workaround. I plan to work on the `exclude_assets` option.

Could you share your YAML workflow or the details of your use case?

**Comment by radames** [comment]
forget my last message, I'm using @pawsong specup/actions-gh-pages@master temporary fix! thanks

**Comment by radames** [comment]
also just realize I could merge the steps of my action and didn't need to have another YAML on gh-pages branch! thanks  But I can see that having you feature to selective exclude_files is a great way to go! rather than hardcode filtering `.github` thanks

**Comment by peaceiris** [comment]
Thank you for your feedback!

**Comment by peaceiris** [comment]
The beta v3.7.0-5 has been released. Could someone test this? CC: @diauweb

The `exclude_assets` option has `.github` by default.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.0-5
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    exclude_assets: ''  # Set empty to deploy .github
    # exclude_assets: 'exclude-file1,exclude-file2'  # Split multi files or directory with comma
```

**Comment by Legion2** [comment]
The `@actions/glob` package can be used to handle the glob patterns. It supports different patterns to include and exclude files https://github.com/actions/toolkit/tree/master/packages/glob#patterns.

**Comment by diauweb** [comment]
v3.7.0-5 is working for me now

**Comment by peaceiris** [comment]
The beta v3.7.0-6 has been released. `exclude_assets` supports glob patterns.

Could someone test this?

The `exclude_assets` option has `.github` by default.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.0-6
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    # exclude_assets: ''  # Set empty to deploy .github
    # exclude_assets: 'exclude-file1,exclude-file2'  # Split multi files or directory with comma
    exclude_assets: '.github,should-exclude-file.txt,should-exclude-dir/**'
```
