### ISSUE TITLE
Add GPG signing support

### ISSUE THREAD

**Issue by Unbinilium** [peaceiris/actions-gh-pages#164]
**Is your feature request related to a problem? Please describe.**
It not related with any problem, just a feature.

**Describe the solution you'd like**
Using GPG or S/MIME created sign tags and commits, and marked commits to GitHub Pages branch as verified on GitHub like this:

```shell
git config --global user.signingkey KEYID
git config --global commit.gpgsign true
```

Anyway, the `gpg_private_key` should be added before creating the commits.

**Additional context**
Ref: 
[https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification](https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification)

[https://github.com/samuelmeuli/action-maven-publish](https://github.com/samuelmeuli/action-maven-publish)

**Comment by peaceiris** [comment]
That's nice! I will work on this on the weekend.

**Comment by Unbinilium** [comment]
> That's nice! I will work on this on the weekend. The option name `gpg_signingkey` is probably better.

Yeah, I agree and you choose the variable name for the api better. And I added some information above which may did some help, waiting for this awesome feature.

**Comment by peaceiris** [comment]
I have learned the flow of creating a commit with GPG signing, just now, for only on macOS and Ubuntu. The `gpg` command is also available on Actions Windows runner but I do not know that the setting on Windows is the same as other operating systems. We need further investigation.

**Comment by weklost** [comment]
@peaceiris @Unbinilium I just found the [Import GPG](https://github.com/crazy-max/ghaction-import-gpg) action created by @crazy-max and I think it could easily fit in here.

I tested it with another action that deploys with GitHub Pages and the commits signature works very well! Here is a simple snippet of my workflow:

```yml
name: website

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Simple page
        run: |
          mkdir public
          echo "<!doctype html><html><head><title>Test!</title></head></html>" > public/index.html
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v1
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by peaceiris** [comment]
@weklost 
Thank you for suggesting that. I already know that action but I will avoid depending on external actions. It is desired to implement all features in one action for testability and maintainability. (Even the `actions/checkout` have caused trouble for me some times, it changed my mind. Nowadays I do not trust even `actions/checkout`...)

**Comment by lepapareil** [comment]
Hello @peaceiris :)

Just wanted to know if we could reprioritize this issue please ?

**Comment by timerring** [comment]
Hi, I have just adjusted this action and combined with the [crazy-max/ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg), and finally implement the deploy on the github pages with GPG signing! You can check [my result](https://github.com/timerring/blog/commits/main/).

And here is my process:
1. I just introduced `ghaction-import-gpg` action first
2. Adjusted the commit function in  `src/git-utils.ts` of this action, appending the parameter `-S`.
3. Then release a new version via `./release.sh`. And use it substitue origin deploy action.

Finally using the combined workflow works well for me.

Or you can use my adjusted version directly:

> You can check the [full yml configuration here](https://github.com/timerring/actions-gh-pages).

```
- name: Import GPG key # import the gpg key to the github action
  uses: crazy-max/ghaction-import-gpg@v6 # repository https://github.com/crazy-max/ghaction-import-gpg
  with: # I use the subkey to sign the commit, if you use the primary key, you can refer to his repository docs.
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }} # the secret gpg subkey
      passphrase: ${{ secrets.PASSPHRASE }} # the passphrase of the gpg subkey
      git_user_signingkey: true
      git_commit_gpgsign: true
      fingerprint: ${{ secrets.FINGERPRINT }} # the fingerprint of the public subkey you use

- name: Deploy Web
  uses: timerring/actions-gh-pages@v5.0.0 # this is adjusted action from peaceiris/actions-gh-pages, you can use it directly.
  with:
      personal_token: ${{ secrets.PERSONAL_TOKEN }} # the personal token of the github action
      external_repository: your_username/your_repository # your target repository
      publish_branch: main # the branch you want to deploy
      publish_dir: ./public # the directory you want to deploy
      user_name: ${{ secrets.USER_NAME }} # the name of the github action
      user_email: ${{ secrets.USER_EMAIL }} # the email of the github action # ATTENTION: please add your github verified email
      commit_message: ${{ github.event.head_commit.message }}
```

> Don't forget to fulfill the `secret.XXX` variables in repository.

For more details, I have written about the issues that may be encountered in my blog, you can refer [it here](https://timerring.github.io/blog/posts/2024/deploy-github-pages-with-gpg-signing).
