### ISSUE TITLE
Action "not found deploy key or tokens"

### ISSUE THREAD

**Issue by BarryYan** [peaceiris/actions-gh-pages#188]
**Describe the bug**
I created a personal token, but got the error "not found deploy key or tokens"
- My `personal_token`
![image](https://user-images.githubusercontent.com/8463435/77825892-270cfa00-7147-11ea-9123-30e4d968d490.png)
- [YAML file https://github.com/BarryYan/barryyan.github.io/blob/master/.github/workflows/hugo.yml#L36](https://github.com/BarryYan/barryyan.github.io/blob/master/.github/workflows/hugo.yml#L36)

#### Actions run result
```
Run peaceiris/actions-gh-pages@v3
[INFO] : true
[INFO] PublishBranch: master
[INFO] PublishDir: ./p
[INFO] ExternalRepository: 
[INFO] AllowEmptyCommit: false
[INFO] KeepFiles: false
[INFO] ForceOrphan: false
[INFO] UserName: github-actions[bot]
[INFO] UserEmail: 
[INFO] CommitMessage: Deploy commit: Fix action
[INFO] TagName: 
[INFO] TagMessage: 
[INFO] EnableJekyll (DisableNoJekyll): false
[INFO] CNAME: 

##[error]Action failed with "not found deploy key or tokens"
```

**To Reproduce**
No.

**Expected behavior**
It can build success.

**Screenshots**
No.

**Your YAML file**
- [YAML file](https://github.com/BarryYan/barryyan.github.io/blob/master/.github/workflows/hugo.yml)

**Additional context**
No.

**Comment by peaceiris** [comment]
I think you just forgot to add your token as a secret variable. See the official documentation: [Creating and storing encrypted secrets - GitHub Help](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

In addition, your personal token has too many permissions. We need only the `repo` permission.

**Comment by peaceiris** [comment]
And your settings: `` and `` are wrong.

The `publish_branch` should be `gh-pages` and you need `user_email` with `user_name`.

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./p
        publish_branch: gh-pages  
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
```

**Comment by peaceiris** [comment]
Ah, your repo is `*.github.io`. Read the README and follow this section: [Repository type - User and Organization](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-repository-type---user-and-organization)

```yaml
name: Github Pages

on:
  push:
    branches: 
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -D -s src -d ../p

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./p
          publish_branch: master  
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
```

**Comment by peaceiris** [comment]
Actually, we can use an auto-generated GitHub token `github_token: ${{ secrets.GITHUB_TOKEN }}` instead of a personal token.

**Comment by BarryYan** [comment]
I use `github_token`, the auth passed, but had a new error :
```
Run peaceiris/actions-gh-pages@v3
[INFO] GithubToken: true
[INFO] PublishBranch: master
[INFO] PublishDir: ./p
[INFO] ExternalRepository: 
[INFO] AllowEmptyCommit: false
[INFO] KeepFiles: false
[INFO] ForceOrphan: false
[INFO] UserName: github-actions[bot]
[INFO] UserEmail: github-actions[bot]@users.noreply.github.com
[INFO] CommitMessage: Deploy commit: Fix token
[INFO] TagName: 
[INFO] TagMessage: 
[INFO] EnableJekyll (DisableNoJekyll): false
[INFO] CNAME: 

[INFO] setup GITHUB_TOKEN
##[error]Action failed with "You deploy from master to master"
```

**Comment by BarryYan** [comment]
One more issue, after Github Action deployed, it seemed filter `.html` files, did deployed to `master`,
there are files in [ `master`](https://github.com/BarryYan/barryyan.github.io/tree/master)

**Comment by peaceiris** [comment]
That is a problem with the git submodule. The `actions/checkout@v2` action needs `submodules: true` or `submodules: recursive` to checkout submodules.

```yaml
- uses: actions/checkout@v2
  with:
    submodules: true
```
