### ISSUE TITLE
Add support for absolute paths

### ISSUE THREAD

**Issue by koppor** [peaceiris/actions-gh-pages#242]
```yml
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: /tmp/out
```

Results in

```text
 ENOENT: no such file or directory, scandir '/home/runner/work/user-documentation/user-documentation/tmp/out'
```

I assume that the first slash is just stripped?

**Comment by peaceiris** [comment]
It comes from this line: https://github.com/peaceiris/actions-gh-pages/blob/c1bc06c3e6c64d6663aaaddce19c3092f44fee76/src/git-utils.ts#L40-L43

Currently, this action just supports the directories under the `${GITHUB_WORKSPACE}`. We will support the absolute path.

**Comment by misfir3** [comment]
FYI, I also get this same error when using the relative `./public` path, but my hugo files are also one level in, so in my actions workflow, I do the following:

```
      # change dir and build
      - name: Build
        run: cd hugo-dir && hugo --cleanDestinationDir && cd ../

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
```

**Comment by peaceiris** [comment]
@misfir3 There is a misunderstanding about a step. For each step starts from `GITHUB_WORKSPACE` so `cd ../` is not necessary. The correct setting is the following:

```yaml
      - name: Build
        run: cd hugo-dir && hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-dir/public
```
