### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by igaryhe** [peaceiris/actions-gh-pages#25]
The current version of the action seems like it doesn't support custom domain. It would be great if we could set the CNAME via the deploy command.

**Comment by peaceiris** [comment]
How about the following?

```yaml
    - name: Build
      run: |
        hugo --gc --minify --cleanDestinationDir
        cp ./path/to/CNAME ./public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

And, most of the Static Site Generators can support `CNAME` as static files.

- [Use a Custom Domain | Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain)
- [Using the Static folder | GatsbyJS](https://www.gatsbyjs.org/docs/static-folder/)

> [How Gatsby Works with GitHub Pages | GatsbyJS](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/)
>
> Note: Don’t forget to add your CNAME file to the static directory.

The same may be said of other files (`.nojekyll` `BingSiteAuth.xml` `robots.txt`). I think that it is better to manage those files by Static Site Generators.
