### ISSUE TITLE
Deploy step succeeded but the gh-pages branch not updated

### ISSUE THREAD

**Issue by Jeff-Tian** [peaceiris/actions-gh-pages#27]
Please help check https://github.com/Jeff-Tian/thesis-paper/actions, there are many actions, each of them says deploy succeeded, but you can check https://github.com/Jeff-Tian/thesis-paper/tree/gh-pages there is only 1 commit.

**Comment by peaceiris** [comment]
Please try the following.

```diff
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./
+      with:
+        emptyCommits: true
```

It seems to be a bug. I will investigate and fix it.

**Comment by kingofzeal** [comment]
I notice the info statement reporting the value of that variable is blank, which is odd given the parameter should default to "true" if nothing is provided ([docs page](https://help.github.com/en/articles/metadata-syntax-for-github-actions#inputs)).

With that being said, there are changes reported by the commit step, so the flag shouldn't prevent the deployment, regardless of what the flag is set to. I'm wondering if there's an order of operations issue with that block which is causing it to exit before the push command is made. In other words, I'm wondering if this would help as well:

```diff
git commit -m "${COMMIT_MESSAGE}" || \
-        print_info "No changes detected, skipping deployment" && \
-        exit 0
+        (print_info "No changes detected, skipping deployment" && \
+        exit 0)
```

Otherwise the direction you are going with the PR should also fix the flag being incorrectly interpreted.

**Comment by peaceiris** [comment]
I will fix this by #28 

And I found it that inputs were not defined when we use a docker image from Docker Hub without `with` statement.

### INPUT_EMPTYCOMMITS were not defined

- https://github.com/peaceiris/hugo-test-project/commit/f21f4cc80f318b040f622edf992f75a5d3d1caf2/checks#step:6:6

```yaml
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

```
-e PERSONAL_TOKEN -e PUBLISH_BRANCH -e PUBLISH_DIR -e HOME
```

### INPUT_EMPTYCOMMITS were defined

- `emptyCommits: true` https://github.com/peaceiris/hugo-test-project/commit/50360fbe2272dcb492395f91172c4757f8236d22/checks#step:6:8
- `emptyCommits: false` https://github.com/peaceiris/hugo-test-project/commit/ef39a04b138b56a0bfe0715674789ac17e90eefd/checks#step:6:8

```yaml
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: true
        # emptyCommits: false
```

```
-e PERSONAL_TOKEN -e PUBLISH_BRANCH -e PUBLISH_DIR -e INPUT_EMPTYCOMMITS -e HOME
```

I will ask this behavior at the GitHub Community forum.
