### ISSUE TITLE
Support specifying the full commit message

### ISSUE THREAD

**Issue by dtolnay** [peaceiris/actions-gh-pages#274]
I am interested in using this Action, but I'd like to have complete control of the commit message of the resulting commit. The `commit_message` input described in https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-custom-commit-message allows setting a prefix of the commit message but the following code subsequently unconditionally appends the 40-character commit hash from the source commit onto that:

https://github.com/peaceiris/actions-gh-pages/blob/750c807fa1ecf9d3d455cfd0fb5533442c660a1e/src/git-utils.ts#L148-L154

Would it be possible to expose control over the full message in a way that disables appending that hash?

Tentative proposal that would work for my use case, but open to others:

```yaml
uses: peaceiris/actions-gh-pages@v3
with:
  full_commit_message: ...
```

**Comment by peaceiris** [comment]
The current specification is for using GitHub's ability to display commit hash information like the following.

<img width="519" alt="Screen Shot 2020-05-04 at 7 42 55" src="https://user-images.githubusercontent.com/30958501/80927761-f6218400-8dda-11ea-83b2-4d82fa8b9694.png">

Is there a problem with including a commit hash that fired a deployment in a commit message? Can you explain the problem in detail?
If solving that problem will improve anything, I will be happy to do so.

If we add that new feature, I'm going to implement it in the following way.

```yaml
- uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    commit_message: ${{ github.event.head_commit.message }}
    commit_message_nohash: true
```

**Comment by dtolnay** [comment]
I am including the hash myself, except it is not at the end and it uses `rev-parse --short` to keep the total length under control for command line users where GitHub's displaying doesn't play a role.

```yaml
# steps:

- id: rev
  run: echo ::set-output name=rev::$(git rev-parse --short HEAD)
- uses: peaceiris/actions-gh-pages@v3
  with:
    commit_message: Docs for ${{steps.rev.outputs.rev}} -- ${{github.event.head_commit.message}}

**Comment by peaceiris** [comment]
The v3.6.0 has been released and the v3 tag also updated. Could you try it?

```
- uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    full_commit_message: ${{ github.event.head_commit.message }}
```

<img width="403" alt="Screen Shot 2020-05-04 at 9 53 09" src="https://user-images.githubusercontent.com/30958501/80930268-781aa880-8ded-11ea-82d5-230d185bedc8.png">
