### ISSUE TITLE
INPUT_EMPTYCOMMITS is not defined with a docker image from Docker Hub

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#29]
I will fix this by #28 

And I found it that inputs were not defined when we use a docker image from Docker Hub without `with` statement even though we defined [emptyCommits default true](https://github.com/peaceiris/actions-gh-pages/blob/0713c6cb9cdc09ac59411494156c5ba2b06c78f8/action.yml#L14)

I will ask about this behavior at the GitHub Community forum.

### INPUT_EMPTYCOMMITS were not defined

- https://github.com/peaceiris/hugo-test-project/commit/f21f4cc80f318b040f622edf992f75a5d3d1caf2/checks#step:6:6

```yaml
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

```
-e PERSONAL_TOKEN -e PUBLISH_BRANCH -e PUBLISH_DIR -e HOME
```

### INPUT_EMPTYCOMMITS were defined

- `emptyCommits: true` https://github.com/peaceiris/hugo-test-project/commit/50360fbe2272dcb492395f91172c4757f8236d22/checks#step:6:8
- `emptyCommits: false` https://github.com/peaceiris/hugo-test-project/commit/ef39a04b138b56a0bfe0715674789ac17e90eefd/checks#step:6:8

```yaml
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: true
        # emptyCommits: false
```

```
-e PERSONAL_TOKEN -e PUBLISH_BRANCH -e PUBLISH_DIR -e INPUT_EMPTYCOMMITS -e HOME
```

_Originally posted by @peaceiris in https://github.com/peaceiris/actions-gh-pages/issues/27#issuecomment-533805867_
