### ISSUE TITLE
Deploy from master branch to other master branch

### ISSUE THREAD

**Issue by klakegg** [peaceiris/actions-gh-pages#318]
### Describe the bug

Deployment from `master` branch of one repo to `master` branch of other repo failes with the following error:

```
##[error]Action failed with "You deploy from master to master"
```

### To Reproduce

```
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SUPER_GITHUB_TOKEN }}
          external_repository: [other repo]
          publish_dir: target/site
          publish_branch: master
```

### Expected behavior

Allow deploying to other `master`branch when `external_repository` is set.

### Your YAML file

See above.
