### ISSUE TITLE
New Option destination_dir for deploying to a subdirectory

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#324]
### Is your feature request related to a problem? Please describe

Some users seem to want to deploy to a subdirectory.

### Describe the solution you'd like

Add a new option `destination_dir` for setting a directory name.

### Describe alternatives you've considered

We can use the option `keep_files` in this case already. But it seems to be a little difficult for users to understand the behavior.

```yaml
- name: Setup assets
  run: |
    mkdir public subdir1
    mv your_contents ./subdir1/
    mv ./subdir1 ./public/

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    keep_files: true
```

After we get the `destination_dir` option, the above steps will be merged into one as follows.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    destination_dir: ./subdir1
```

### Additional context

It seems tedious to implement and test it in consideration of a variety of situations.

To be investigated:

- [x] #507 Weird nesting of content folders

**Comment by peaceiris** [comment]
The v3.7.0-0 has been released as a beta release.

**Comment by peaceiris** [comment]
The v3.7.0-1 has been released as a beta release.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.1-0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: subdir
```

**Comment by peaceiris** [comment]
#410 was opened

**Comment by peaceiris** [comment]
The v3.7.0-4 has been released as a beta release.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.1-4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: subdir
```

**Comment by rscohn2** [comment]
I defined an environment variable to be BRANCH_NAME and wanted to use that for the destination_dir:

destination_dir: ${BRANCH_NAME}

but it doesn't do expansion.

I got the behavior I wanted with keep_files:
cp -r build/html public/${BRANCH_NAME}

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3.7.0-6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        keep_files: true

**Comment by peaceiris** [comment]
I highly recommend you to read the GitHub Actions official documentation before you go. You can know the basic syntax of the Actions workflow.

```yaml
- name: Set branch name
  id: branch
  run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.0-6
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: ${( steps.branch.outputs.BRANCH_NAME }}
```

**Comment by dopplershift** [comment]
Thanks for the work on this action and this new feature which is *exactly* what I need to use this to deploy versioned docs to GH Pages. Unfortunately, I cannot for the life of me get this to work properly (with 3.7.0-6 or -7). Here's what my base config looks like:
```yaml
    - name: Upload to GitHub Pages
      if: ${{ github.event_name != 'pull_request' && matrix.experimental == false }}
      uses: peaceiris/actions-gh-pages@v3.7.0-7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html/
        exclude_assets: '.buildinfo'
        destination_dir: ./${{ env.DOC_VERSION }}
        keep_files: false
        full_commit_message: Deploy ${{ env.DOC_VERSION }} to GitHub Pages
```
(env.DOC_VERSION is dev in this case) with that config I [end up with](https://github.com/Unidata/MetPy/runs/962166561?check_suite_focus=true):
```
  [INFO] copy units.html
  [INFO] delete excluded assets
  [INFO] first deployment, create new branch gh-pages
  ENOENT: no such file or directory, uv_cwd
  /usr/bin/git init
  Reinitialized existing Git repository in /home/runner/actions_github_pages_1596913915535/.git/
  /usr/bin/git checkout --orphan gh-pages
  fatal: A branch named 'gh-pages' already exists.
  ##[error]Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
so it's not a first deployment, but I think because copying & deleting fails, that's detected as "first deployment". Some googling around on the `ENOENT...uv_cwd` makes me think it's failing because the current working directory was deleted. My guess is the git command used to delete all the old files is deleting the target directory, which is also the CWD at that point.

If I switch to use `keep_files: true`, then I don't have the deletion problem, but I have a different problem. In the source I have a directory e.g. `docs/build/html/_downloads/abcdef/myfile.py`. This file already exists on the gh-pages branch at `dev/_downloads/abcdef/myfile.py`. After the deployment pushes, I have an additional copy at `dev/_downloads/_downloads/abcdef/myfile.py`. This happens for any file in a subdirectory as far as I can tell. The only things copied/updated properly are in the base `docs/build/html/` going to `dev/`.

Any help would be appreciated, because it would be really cool to be able to use this action. Thanks!
