### ISSUE TITLE
output final commit sha

### ISSUE THREAD

**Issue by trim21** [peaceiris/actions-gh-pages#348]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

```js
core.setOutput('sha', sha)
```

so user can access this commit by `${{ steps.gh-pages.outputs.sha}}`

**Comment by peaceiris** [comment]
Thank you for suggesting this!

Yes. That looks useful. A longer option name may be easier to understand as follows.

```js
core.setOutput('pages_commit_hash', sha);
```

I also considered the following output parameter names.

- `published_commit_hash`
- `deployed_commit_hash`
- `generated_commit_hash`

We want to differentiate a `publish_branch`'s commit hash from source branch's one. Does anybody have any better ideas of the output parameter name? Please tell us here!

I will work on this with #300, #344, and others.

**Comment by sidvishnoi** [comment]
How about `src_sha` and `dst_sha`?

**Comment by peaceiris** [comment]
Cool!

We already have `${{ github.sha }}` in the GitHub Actions contexts. (src_sha)

The GitHub Actions context uses `github.sha` so we will choose `dst_sha`. (destination)

Thanks @sidvishnoi

**Comment by peaceiris** [comment]
Could someone test the branch `feat-sha` as follows?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@feat-sha
  id: pages
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}

- run: echo ${{ steps.pages.outputs.dst_sha }}
```
