### ISSUE TITLE
Enhancement: Deploy to other repo

### ISSUE THREAD

**Issue by skyfrk** [peaceiris/actions-gh-pages#35]
Hello @peaceiris , thank you for developing this GitHub Action!

Here's my enhancement suggestion: I want to be able to deploy the build artifact from repo `A` to the GitHub Pages branch of repo `B`.

Use case: If you develop a website in a private GitHub repo that you want to deploy to your user github page (`<username>.github.io`) you have to deploy from repo `A` to repo `B`.

Suggestion: Replace `GITHUB_REPOSITORY` with a custom configurable variable.

**Comment by peaceiris** [comment]
Did you try the following?

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
        GITHUB_REPOSITORY: <username>.github.io
```

Maybe, It works.

**Comment by skyfrk** [comment]
I tried this:

```yaml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        GITHUB_REPOSITORY: skyfrk/skyfrk.github.io
```

Which should be the correct [syntax](https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables) but it didn't work:

```shell
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I added the public key to `skyfrk/skyfrk.github.io` and the private key as a secret to my test repo. I checked for typos...

But even if it worked I don't think that this is the best approach to solve this issue. :/
