### ISSUE TITLE
Support for publish_branch that is the same as the triggering branch?

### ISSUE THREAD

**Issue by trang1618** [peaceiris/actions-gh-pages#358]
Currently, we're getting the [following error](https://github.com/EpistasisLab/penn-ml-benchmarks/runs/785700840#step:8:33) for [this CI config](https://github.com/EpistasisLab/penn-ml-benchmarks/blob/97280e2b5606c0702f24e103123ed0ccba526c43/.github/workflows/pythonapp.yml#L41-L49):

```
Setup auth token
  [INFO] setup GITHUB_TOKEN
  ##[error]Action failed with "You deploy from PMLB2.0 to PMLB2.0"
```

From https://github.com/peaceiris/actions-gh-pages/issues/245, it sounds like this is the intended behavior to:

> When users set a `publish_branch` that is the same as a branch triggered by the workflow, this action stops the deployment to protect the branch.

In our case, we use CI to regenerate some files. The use case is similar to linting. Imagine CI is used to lint files that should be committed back to the same branch.

What are the reasons that publishing to the triggering branch is forbidden? Is there a workaround?

**Comment by peaceiris** [comment]
When you set a branch name as the same as the triggering branch, it will overwrite all files with the files under the `publish_dir`. We cannot run the next CI on the branch.

I read your YAML but I do not understand what you want to do. Do you know the GitHub Pages spec and basic usage? Could you tell me what is your deployment assets?

**Comment by peaceiris** [comment]
> What are the reasons that publishing to the triggering branch is forbidden?

Let's imagine a project powered by Static Site Generators. We are managing source files (Markdown and template files) and generating output files like HTML, CSS, and JavaScript files. In this case, when we set a branch name as the same as the triggering branch, it will overwrite all Markdown files with the HTML files under the publish_dir. We cannot run the next CI on the branch.

**Comment by trang1618** [comment]
Prior to deployment, CI rebuilds READMEs that change when data ends up changing. We want the READMEs on a branch to automatically update when the data on that branch change.

Copying the relevant section of our workflow:

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # external_repository: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: ${{ env.BRANCH }}
        # without keep_files, .github/workflows/pythonapp.yml was removed
        keep_files: true
```

> it will overwrite all files with the files under the publish_dir

That is the goal. When CI changes a file, we want that change to be pushed back to the triggering branch.

> We cannot run the next CI on the branch.

We don't want CI to run on the CI-generated commit, although it's not terrible if it does, since there shouldn't be any new changes and deployment would therefore be skipped. Setting `keep_files: true` ensures the `.github` directory is not removed.

> it will overwrite all Markdown files with the HTML files under the publish_dir. We cannot run the next CI on the branch.

In our case, we set `publish_dir: .`. I don't think deployment to triggering branches makes sense unless publish_dir is the repository root.
