### ISSUE TITLE
Update: readme

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#37]
I found it. The following step will work well for only **private** repo. And there is no docker build step, it completes fast.

```yaml
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages # or master
        PUBLISH_DIR: ./public
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.4.0/entrypoint.sh
        bash ./entrypoint.sh
```

For private repositories, the above approach works well but **public repositories failed**.

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

The above (use action) also works well for only private repo.

_Originally posted by @peaceiris in https://github.com/peaceiris/actions-gh-pages/issues/9#issuecomment-536869265_

---

- [x] change: ssh key path for script mode.
- [x] docs: Add new section `script mode`
- [x] docs: Add `GITHUB_TOKEN` for only private repo.
