### ISSUE TITLE
Additional publish_dir:

### ISSUE THREAD

**Issue by mitm001** [peaceiris/actions-gh-pages#370]
### Is your feature request related to a problem? Please describe
I use a site generator (Antora) that doesn't include certain folders or files in the build process unless they are inside a predetermined static folder structure, so they do not get published to the gh-pages branch if outside these folders.

### Describe the solution you'd like
I would like to include an additional publish_dir so that these folders outside this static structure, if changes are present, will be included in the commit to the gh-pages branch.

### Describe alternatives you've considered
I have tried:
```
publish_dir: |
    ./build/site
    ./docs/resources
```

```
publish_dir: ./build/site
publish_dir: ./docs/resources
```

```
publish_dir: [./build/site, ./docs/resources]
```

### Additional context

Using an array would be easiest.

If this is already possible, or there is a better way, please advise.

**Comment by peaceiris** [comment]
We can already do it.

```yaml
- name: build
   run: do_some_build_stuff

- name: Add resources
   run: cp ./docs/resources ./build/site/

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./build/site
```
