### ISSUE TITLE
github_token not working on private repo

### ISSUE THREAD

**Issue by chatziko** [peaceiris/actions-gh-pages#377]
`github_token` are supposed to work with private repos since some time now, but the following config is not working reliably.
```
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public
        force_orphan: true
```
What happens:
- the action runs succesfully
- the correct output is pushed correctly in the master branch
- the gihub pages Activity log shows that the new version is deployed
- but the __old__  version is still served
  - not always, but with substantially high probability (say 30-50% of the time)
- if I manually commit any file in the master branch the new version is immediately served.
- setting `force_orphan: false` does __not__ fix the issue

For now I'm switching back to `deploy_key`, but it would be super neat to fix this.
