### ISSUE TITLE
Can't overwrite files on the branch with the action

### ISSUE THREAD

**Issue by illright** [peaceiris/actions-gh-pages#390]
# Describe the bug

My CI is set up to deploy pull requests to separate folders to allow previewing changes. I've run into an issue while trying to push subsequent commits onto a pull request branch that has already been deployed. 

On the **Prepare publishing assets** step ([this line of code](https://github.com/peaceiris/actions-gh-pages/blob/4d89a385db8421a90a755e655201bfbb8e037f7d/src/git-utils.ts#L69)) it is trying to copy the assets over the previously existing ones, and even though `force` is set to `true` while copying, it still fails with `EEXIST: file already exists`.

This failure is (probably mistakenly) treated as a failure to check out a branch, which causes the action to try and create a new branch, which doesn't work because the branch, in fact, exists.

### To Reproduce

1. Set up deploying on pull requests ([workflow file here](https://github.com/illright/attractions/actions/runs/164325161/workflow))
2. Create a pull request and let it deploy
3. Push more commits to the same branch

### Expected behavior

The action should empty out the directory that stores files for this PR, then freshly copy over the new assets

### Your YAML file

https://github.com/illright/attractions/blob/develop/.github/workflows/pr_demo.yml

### Additional context

Here's the link to the failed job logs:
https://github.com/illright/attractions/runs/857251843?check_suite_focus=true

**Comment by peaceiris** [comment]
Now, this use case is not supported.
Related to #324

**Comment by illright** [comment]
Actually, there is a simple workaround. The failure is due to the GitHub's Action toolkit's unexpected behaviour with copying stuff. `io.cp` uses a custom implementation of `mkdirP` under the hood, which fails with an error when trying to create an existing directory.

The workaround is to forcefully remove the file at `filePath` (if it happens to exist) right before [doing the copy operation](https://github.com/peaceiris/actions-gh-pages/blob/4d89a385db8421a90a755e655201bfbb8e037f7d/src/git-utils.ts#L24). 

It won't achieve the desired behaviour fully, since the subdirectory of deployment will still contain old files that weren't overwritten, but for most use cases this is going to be just fine, because the build should complete successfully.

**Comment by peaceiris** [comment]
I plan to replace the copy operation with another and will also consider this. 👍 
Related to #103 #163

**Comment by peaceiris** [comment]
The v3.7.0-0 has been released as a beta release. Could you try it?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.0-0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: subdir
```

**Comment by peaceiris** [comment]
The v3.7.0-1 has been released as a beta release.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.1-1
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: subdir
```

**Comment by peaceiris** [comment]
The v3.7.0-4 has been released as a beta release.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.7.0-4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    destination_dir: subdir
```
