### ISSUE TITLE
Prohibited branch incorrect detection

### ISSUE THREAD

**Issue by zachbryant** [peaceiris/actions-gh-pages#393]
### Describe the bug

The prohibited branch detection prohibits branches that include the publish branch, but do not equal the publish branch. For example, my branch name is `gh-pages-redesign` and I want to publish to `gh-pages`, but this is prohibited.

### To Reproduce

1. Create branch `gh-pages` and `gh-pages-redesign`
2. Push changes to `gh-pages-redesign`
3. Attempt to deploy to `gh-pages`

### Expected behavior

Deploy as normal, don't error out.

### Your YAML file

```yaml
name: Publish to Github Pages
on:
  push:
    branches:
      - gh-pages-redesign

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - name: Install dependencies
        run: |
          npm install
          npm install --only=dev
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          keep_files: false
```

### Additional context

![image](https://user-images.githubusercontent.com/32501288/87360172-5f7deb80-c51e-11ea-9313-40067a9eef5d.png)

The problem is in `src/set-tokens.ts` on line 86:
```javascript
86    isProhibitedBranch = ref.includes(`refs/heads/${publishBranch}`);
```

it should check that the branch name is exact with nothing else appended
```javascript
isProhibitedBranch = ref.match(new RegExp(`refs/heads/${publishBranch}$`));
```
