### ISSUE TITLE
Although `enable_jekyll` is set to false (by default), I don't see a `.nojekyll` file.

### ISSUE THREAD

**Issue by dimitribouniol** [peaceiris/actions-gh-pages#437]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

This is my first time using a workflow, and I'm surprised how easy this made getting a quick site up and running! That said, I did notice that although `enable_jekyll` is set to false (by default), I don't see a `.nojekyll` file in the resulting repo (The one I had placed previously was actually removed). According to https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-enable-built-in-jekyll-enable_jekyll, this should just work.

Here are the inputs from my run:
```
 Deploy to GitHub Pages 5s
31
  
1
Run peaceiris/actions-gh-pages@v3
15
Dump inputs
16
  [INFO] DeployKey: true
17
  [INFO] PublishBranch: main
18
  [INFO] PublishDir: ./Output
19
  [INFO] ExternalRepository: example/example.github.io
20
  [INFO] AllowEmptyCommit: false
21
  [INFO] KeepFiles: false
22
  [INFO] ForceOrphan: false
23
  [INFO] UserName: 
24
  [INFO] UserEmail: 
25
  [INFO] CommitMessage: Added GitHub Action to auto deploy the site
26
  [INFO] FullCommitMessage: 
27
  [INFO] TagName: 
28
  [INFO] TagMessage: 
29
  [INFO] EnableJekyll (DisableNoJekyll): false
30
  [INFO] CNAME: example.com
```

I hope I just missed something silly!

### Link to your contents

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup JohnSundell/Publish
        run: |
          cd ${HOME}
          git clone --depth=1 https://github.com/JohnSundell/Publish.git
          cd ./Publish
          swift build -c release
          echo "::add-path::${HOME}/Publish/.build/release"

      - run: publish-cli generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: example/example.github.io
          publish_branch: main
          publish_dir: ./Output
          cname: example.com
          commit_message: ${{ github.event.head_commit.message }}
```

### Screenshots

<img width="413" alt="image" src="https://user-images.githubusercontent.com/225505/89112295-8e98c600-d415-11ea-88d3-d65007f3dccb.png">
