### ISSUE TITLE
Enhancement proposal: dry run / test mode

### ISSUE THREAD

**Issue by vincerubinetti** [peaceiris/actions-gh-pages#451]
[npm-publish](https://docs.npmjs.com/cli/publish) has a nice feature called `--dry-run` that lets you test what the command is going to do without actually doing it. It might be nice to have something like that in `actions-gh-pages`.

It could look like this:

```yaml
name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # blah blah blah
      - name: Set up Node # blah blah blah
      - name: Install packages # blah blah blah
      - name: Build app # blah blah blah
      - name: Test deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'pull_request' # on pull request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' # on push to master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

That way, on each pull request, I can see if this `actions-gh-pages` step in the CI workflow has any problems, and gain confidence that it will work fine when pushing/merging into master.

**Comment by peaceiris** [comment]
Thank you for the suggestion. Good idea.

I'm assuming usage like the following.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    dry_run: ${{ github.event_name == 'pull_request' }}
```

**Comment by peaceiris** [comment]
Could you test the branch `feat-dry-run` as follows?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@feat-dry-run
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    dry_run: ${{ github.event_name == 'pull_request' }}
```
