### ISSUE TITLE
Prevent empty commits happen

### ISSUE THREAD

**Issue by kwladyka** [peaceiris/actions-gh-pages#47]
**Is your feature request related to a problem? Please describe.**
Sometimes I add commits to `master` which don't change `gh-pages` output. Empty commits add to `gh-pages` in such case.

Example of such commits: experiment with github actions, re-run github actions, add drafts content etc.

**Describe the solution you'd like**
No add empty commits to `gh-pages`. Just do nothing then.

I generate gh-pages using `peaceiris/actions-hugo@v2.2.2`.

**Comment by peaceiris** [comment]
- [Suppressing empty commits](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-suppressing-empty-commits)

> By default, a commit will always be generated and pushed to the PUBLISH_BRANCH, even if nothing changed. If you want to suppress this behavior, set the optional parameter `emptyCommits` to `false`. cf. Issue #21

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v2.5.0
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
  with:
    emptyCommits: false
```
