### ISSUE TITLE
[error]Action failed with "not found deploy key or tokens"

### ISSUE THREAD

**Issue by missll** [peaceiris/actions-gh-pages#470]
### Describe your question

1. build-deploy
<img width="561" alt="图片" src="https://user-images.githubusercontent.com/20451024/91942941-55ae8280-ed2e-11ea-9deb-10cf1676daef.png">

I really don't know what went wrong,please help me... 

2. my workflow file
```
name: publish blog

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm install vuepress
    - run: npm run build
    
    - name: Deploy to github.io
      uses: peaceiris/actions-gh-pages@v3
      env:
        deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_branch: gh-pages
        publish_dir: .vuepress/dist
```
3. my repository settings
<img width="1015" alt="图片" src="https://user-images.githubusercontent.com/20451024/91942725-f9e3f980-ed2d-11ea-97ab-a97459cfef1f.png">
<img width="952" alt="图片" src="https://user-images.githubusercontent.com/20451024/91942769-0cf6c980-ed2e-11ea-9865-506694e8bcc4.png">

### Link to your contents

[my repository](https://github.com/missll/docs)

[my actions](https://github.com/missll/docs/actions)
