### ISSUE TITLE
Support /docs option with deployments

### ISSUE THREAD

**Issue by GeertvanHorrik** [peaceiris/actions-gh-pages#50]
**Is your feature request related to a problem? Please describe.**

I would like to deploy to `/docs` instead of the `master` or `gh-pages` branch.

**Describe the solution you'd like**

Both the source *and* github pages are located in the master branch:

./src => source of the website
./docs => publish gh-pages website

I would like the files to be deployed to the ./docs folder

**Describe alternatives you've considered**

I've checked whether gh-pages was possible, but I can't find the option in my gh-pages repository:

![image](https://user-images.githubusercontent.com/1246444/68752216-3873c080-0603-11ea-8580-e086923ac2f2.png)

**Additional context**

**Comment by peaceiris** [comment]
What is the advantage of the docs folder? How about migrating your docs folder to the `gh-pages` branch.

**Comment by GeertvanHorrik** [comment]
As a workaround, here is another action that works fine (if you are committing to the same repo):

```
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Automatically generate site" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
```
