### ISSUE TITLE
keep_files creates subdir instead of overwriting contents of same-name dir

### ISSUE THREAD

**Issue by quite** [peaceiris/actions-gh-pages#509]
I'm using this action here, with `keep_files: true` (currently set to `false`) https://github.com/fruktkartan/fruktkartan/blob/master/.github/workflows/deploy-production.yml#L24

I'm quite confident that the latest `v3` deploys `js/file` to `js/js/file`, when the `js` directory already exists (same for `fonts` etc).

**Comment by quite** [comment]
I'm setting `keep_files: false` for now.

**Comment by peaceiris** [comment]
Thanks.

Duplicate of #507 and related to #324

**Comment by peaceiris** [comment]
@hathawayj @quite

Could you test the branch `fix-copy-assets` as follows?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@fix-copy-assets
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    keep_files: true
```
