### ISSUE TITLE
How to deploy to 'protected branches' with this tool?

### ISSUE THREAD

**Issue by JasoonS** [peaceiris/actions-gh-pages#51]
**Is your feature request related to a problem? Please describe.**
It is frustrating that you use a CI/CD tool like this to automate the process and make deploying code easier, but at the same time you require there to be no branch protection on this branch (IE it is still possible to deploy without checks from localhost).

**Describe the solution you'd like**
An explination of how to avoid this issue, or a clear solution.

**Describe alternatives you've considered**
I have considered making another GH user account and adding it to my organization as a "machine" user, this user could then have push permission on the protected branch. But this will use an extra slot for our GH payed account. Please advise.

**Additional context**
This is the exact error I get:
`
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To github.com:wild-cards/ui.git
``

**Comment by peaceiris** [comment]
First of all, we can push to a protected branch with this action by default.

In your case, you enable `At least 1 approving review is required by reviewers`, so we cannot push. As far as I know, there is no any workaround to force push the branches requiring reviews. That is the expected behavior of GitHub Branch protection rules.

**Comment by peaceiris** [comment]
Oh, I could force push to a branch requiring reviews.

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

<img width="876" alt="Screen Shot 2019-11-15 at 8 13 21" src="https://user-images.githubusercontent.com/30958501/68904020-25d2c600-0780-11ea-8aae-38458a2f190f.png">
