### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#52]
Hello, 

In my case I am added as a collaborator (full admin access) to an Organization. I am trying to setup a simple static site push to gh-pages. I have setup using `ACTIONS_DEPLOY_KEY`. The deploy succeeds but the site changes are not reflected. In-fact if I manually delete gh-pages branch and re-run the action, it succeeds again, but the site is never published. All the code seems okay in gh-pages.  What am I doing wrong?  here' s my action yaml

```yaml
name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v1

      - name: Build
        run: |
          rm -rf dist
          rsync -rv --exclude=.git --exclude=.github . dist

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist

```

_Originally posted by @shaunakv1 in https://github.com/peaceiris/actions-gh-pages/issues/9#issuecomment-554864128_
