### ISSUE TITLE
Action fails when inbound and existing excluded assets differ in state

### ISSUE THREAD

**Issue by csuwildcat** [peaceiris/actions-gh-pages#520]
### Describe the bug

When using the excluded asset option, the Action fails if one of the inbound assets differs from the existing set.

### To Reproduce

1. Turned on asset exclusion for `node_modules`
2. Ran Action
3. Deletion task hits a file inside of node_modules that doesn't exist in the current folder
4. Produces the following error: Error: Action failed with "ENOENT: no such file or directory, scandir '/home/runner/actions_github_pages_1602700363975/node_modules/@traptitech/markdown-it-katex/.idea'"

### Expected behavior

The Action should not fail if a directory it tries to delete doesn't exist, it should simply skip it and proceed with deletion of the next directory/file it is directed to.

### Your YAML file

```yaml
name: render-specs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Render
        run: |
          npm install
          node -e "require('spec-up')({ nowatch: true })"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,node_modules/**'
          force_orphan: true
```
