### ISSUE TITLE
'Push the commit or tag' step fails with: "The process '/usr/bin/git' failed with exit code 1" using force_orphan

### ISSUE THREAD

**Issue by csuwildcat** [peaceiris/actions-gh-pages#522]
### Describe the bug

After making an update today, the Action kicked off, but produced the following error in the `Push the commit or tag` step:
```
  /usr/bin/git push origin --force gh-pages
  error: src refspec gh-pages does not match any
  error: failed to push some refs to 'https://github.com/decentralized-identity/presentation-exchange.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

The Action was working just a day or so ago, but produced this error today, and I am not sure why. The only difference was that the push was via an inline change in the main GH repo, and now every run fails at this step, regardless of the change or where it is made.

### To Reproduce

1. Make any update that triggers the Action
2. The `Push the commit or tag` step fails

### Expected behavior

Is able to push the commit it tries to generate.

### Your YAML file

```yaml
name: render-specs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          node -e "require('spec-up')({ nowatch: true })"
          rm -rf node_modules

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
```

**Comment by csuwildcat** [comment]
Could this be because the Action is not creating a local first commit after it instantiates the repo in its virtual env?

**Comment by csuwildcat** [comment]
The reason I mentioned it is that there seems to be a common cause cited in the results I have been looking at from folks who have seen this message outside of this Action, in general git usage:

"The 'src refspec <branch> does not match any' error occurs if you have forgotten to add the files you have changed to a commit and try to push those changes to a remote repository before you make the first commit in your repository."

**Comment by peaceiris** [comment]
I am investigating it now: https://github.com/peaceiris/presentation-exchange/runs/1261984063#step:4:64

**Comment by peaceiris** [comment]
Could you try to use d38d8b3?

```yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@d38d8b3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true
          force_orphan: true
```

**Comment by peaceiris** [comment]
And 3d1f363?

```yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@3d1f363
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true
          force_orphan: true
```
