### ISSUE TITLE
Skip CNAME on forks

### ISSUE THREAD

**Issue by friederbluemle** [peaceiris/actions-gh-pages#545]
Thanks for this action. Is there a way to skip creating the CNAME file on forks only? The deployment will fail for forks since the domain is already taken by the source repo. I don't want to use a CNAME for forks, the default location as generated by GitHub is fine.

Is there a recommended CNAME strategy to allow this action to run on both source and forked repos?

Related issues: #112 #153

**Comment by peaceiris** [comment]
## Suggestion 1

Skip deployment on forks.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  if: github.event.repository.fork == false
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    cname: peaceiris.com
```

## Suggestion 2

Set `cname` to empty on forks.

```yaml
- name: Set CNAME
  id: cname
  run: |
    if [ ${{ github.event.repository.fork }} = 'false' ]; then
      echo "::set-output name=cname::peaceiris.com"
    fi

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
    cname: ${{ steps.cname.outputs.cname }}
```
