### ISSUE TITLE
Please add a `latest` tag to the release

### ISSUE THREAD

**Issue by ziyitony** [peaceiris/actions-gh-pages#566]
### Is your feature request related to a problem? Please describe

I want to use the `latest` version but failed, this is the github actions log:
```
Current runner version: '2.276.1'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20210131.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210131.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `peaceiris/actions-gh-pages@latest`, unable to find version `latest`
Retrying in 29.509 seconds
Failed to resolve action download info. Error: Unable to resolve action `peaceiris/actions-gh-pages@latest`, unable to find version `latest`
Retrying in 29.336 seconds
Error: Unable to resolve action `peaceiris/actions-gh-pages@latest`, unable to find version `latest`
```

### Describe the solution you'd like

add a `latest` tag, so that the action script can keep to the latest version.

### Describe alternatives you've considered

no.

### Additional context

my `gh-pages.yml` file content:
```
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
