### ISSUE TITLE
Deploy action overwrites domain name even though CNAME file is present

### ISSUE THREAD

**Issue by lewisdonovan** [peaceiris/actions-gh-pages#568]
When I push my code, the action runs as expected, but the custom domain in the GitHub Pages settings gets removed. I have a CNAME file in the root of `master` and `gh-pages` branches.

### To Reproduce

Pushing to the master branch, triggering the action below.

### Expected behavior

Custom domain name not being removed from GitHub Pages settings.

### Your YAML file

```
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

Repo: [https://github.com/lewisdonovan/lewisdonovan.github.io](https://github.com/lewisdonovan/lewisdonovan.github.io)

**Comment by lewisdonovan** [comment]
Apologies, I found the solution in #112. Closing this issue.
For anyone looking for a solution, adding the `cname` option to the Deploy action will fix it. See the last line of the below:

```
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: customdomain.com
```
