### ISSUE TITLE
cp: can't create '/github/home/ghpages_5916/.git': File exists

### ISSUE THREAD

**Issue by Eriice** [peaceiris/actions-gh-pages#57]
I have read those similar issue(#53 #45 ). 

But I did not use `github.io` repo as public repository. It is published as a branch.

I want to split the static assets as submodule like `blog/static`, It will occur this error.

If `blog/static` as part of master, it works well.

**Comment by peaceiris** [comment]
Please show me your repository.

**Comment by Eriice** [comment]
> Please show me your repository.

There is the [error commit](https://github.com/Eriice/hugo-blog/commit/514da1b5a61238d2297f39d9295e5201808aa8a0/checks?check_suite_id=342328114) when `blog/static` as submodule.

There is the [success commit](https://github.com/Eriice/hugo-blog/commit/53e9b900c78e0a7ed8e5c04467461fb2cc44f923/checks?check_suite_id=342342484) when I remove that submodule.

**Comment by peaceiris** [comment]
Try the following.

- Add `find ./public -name ".git" -type d -delete`
- Fix `PUBLISH_BRANCH`

```yaml
    - name: Hugo blog CI
      run: |
        hugo -D
        find ./public -name ".git" -type d -delete

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

**Comment by Eriice** [comment]
> Try the following.
> 
> * Add `find ./public -name ".git" -type d -delete`
> * Fix `PUBLISH_BRANCH`
> 
> ```yaml
>     - name: Hugo blog CI
>       run: |
>         hugo -D
>         find ./public -name ".git" -type d -delete
> 
>     - name: Deploy
>       uses: peaceiris/actions-gh-pages@v2.5.0
>       env:
>         PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
>         PUBLISH_BRANCH: gh-pages
>         PUBLISH_DIR: ./public
> ```

Thanks for your help, it works well.

And I have tried different combinations about `delete .git` and `change branch name`. The key is change the name of branch.

**Comment by Eriice** [comment]
But when I try to commit again with same branch, it occur error.

**Comment by peaceiris** [comment]
As I wrote the README, it is better to filter the trigger branch.

```yaml
on:
  push:
    branches:
    - master
```
