### ISSUE TITLE
How to add `dist/` directory?

### ISSUE THREAD

**Issue by Neos21** [peaceiris/actions-gh-pages#570]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

- My project file tree:

```
my-repository/
|- index.html ... entrypoint
|- src/ ... source codes
|- dist/ ... created by `$ npm run build`
```

- `.gitignore`

```
node_modules/

dist/
```

`index.html` is located in project root directory.
So I want to upload to gh-pages like this:

```
https://example.github.io/my-repository/index.html
https://example.github.io/my-repository/dist/bundle.js
```

Therefore, I wrote workflows like this:

```yaml
name: Deploy To GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run : npm install
      - name: Build
        run : npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '.'
          # to include `./index.html`
```

I expected to include `dist/`.
But `dist/` did not include because `dist/` is specified in `.gitignore`.

How to include `dist/` in gh-pages?

**Comment by peaceiris** [comment]
I recommend you to include all assets into the dist directory and change the `publish_dir`.

```yaml
      - name: Build
        run : npm run build
      - name: Copy assets
        run: cp ./index.html ./dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'dist'
```

**Comment by Neos21** [comment]
Thank you the comment.
For the convenience of existing SPA and Webpack settings, `index.html` loads `dist/bundle.js`.
Is there any other way?

**Comment by peaceiris** [comment]
You can create a new directory (e.g. `public`), move `index.html` and `dist` into `public`, and set `publish_dir: 'public'`.

```yaml
      - name: Build
        run : npm run build
      - name: Create public
        run: |
          mkdir public
          mv ./index.html ./dist ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'public'
```
