### ISSUE TITLE
push success, but nothing only one file: .nojekyll

### ISSUE THREAD

**Issue by sinkcup** [peaceiris/actions-gh-pages#599]
### Describe the bug

push code success, but nothing only one file: `.nojekyll`

### To Reproduce

1. use this flow https://github.com/laravel-fans/laravel-docker/actions/runs/736101982/workflow
2. run it https://github.com/laravel-fans/laravel-docker/runs/2313098756?check_suite_focus=true

### Expected behavior

upload PHP code to branch `laravel-8`

### Screenshots

![image](https://user-images.githubusercontent.com/4971414/114274000-11672b80-9a4f-11eb-827c-5cec69e4523e.png)

![image](https://user-images.githubusercontent.com/4971414/114273909-aa497700-9a4e-11eb-8726-f7bd077c9dc8.png)

### Your YAML file

```
name: Laravel 8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:8.0-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.1.0

      - name: PHPUnit
        run: |
          apt update
          apt install -y libzip-dev unzip
          pecl install xdebug
          docker-php-ext-enable xdebug
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer require orchestra/testbench:^v6 --dev
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-filter src/ tests/
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          name: laravel-8

      - name: install in real Laravel project
        run: |
          rm -rf laravel-demo
          composer create-project --prefer-dist laravel/laravel laravel-demo "8.*"
          cd laravel-demo && composer require --dev laravel-fans/docker:dev-${CI_HEAD_REF_SLUG} && php artisan docker:publish
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: laravel-demo
          path: laravel-demo

  push-demo:
    name: Push Demo Code
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: laravel-demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: laravel-demo
          publish_branch: laravel-8
          allow_empty_commit: true
```

**Comment by peaceiris** [comment]
You just forgot the `actions/checkout`.

**Comment by peaceiris** [comment]
Please check `ls -la ./laravel-demo` before deploymentent, the `laravel-demo` is an empty directory, I think.

**Comment by peaceiris** [comment]
The setting `publish_dir: .` will work well. The `actions/download-artifact` download and expand contents into a current directory.

**Comment by lemosyj** [comment]
I am having the same problem as @sinkcup. My .yml file is as follows:
```
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: pattern-lab
          publish_dir: ./design/pattern-lab/public
          allow_empty_commit: true
```
Files are pushed to my `main` branch correctly, but all I get in my `pattern-lab` branch is the .nojekyll file.
