### ISSUE TITLE
matrix execution fails due to "remote contains work that you do not have locally"

### ISSUE THREAD

**Issue by francesco-ballarin** [peaceiris/actions-gh-pages#608]
Hi,
I have a [workflow](https://github.com/FEMlium/FEMlium/blob/main/.github/workflows/ci.yml) with a matrix strategy, composed of four different cases which run in parallel.

I am randomly getting errors

Push the commit or tag
```
  /usr/bin/git push origin gh-pages
  To https://github.com/FEMlium/femlium.github.io.git
   ! [rejected]        gh-pages -> gh-pages (fetch first)
  error: failed to push some refs to '***github.com/FEMlium/femlium.github.io.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```
(e.g. in https://github.com/FEMlium/FEMlium/runs/2519718493?check_suite_focus=true)

I guess this happens when two jobs are trying to push to the repository at almost the same time. 
Is there a way to force the action to do a git fetch before it tries to do a git push?

My error is quite close to #104, but I think my workflow is different than the one reported there.
The one reported there was having a multi-execution of the action in the same workflow; instead I have a single execution of the action in parallel workflows.

Thanks!

**Comment by peaceiris** [comment]
This is related to #605

Your case touches a Git core concept. To resolve this, we can implement a retry process. But since it is complex to determine which one is the latest commit, I do not that.

## A Recommended Workflow

Fortunately, I know that we can enhance the workflow to avoid such errors. [actions/upload-artifact](https://github.com/actions/upload-artifact) and [actions/download-artifact](https://github.com/actions/download-artifact) are useful. Specifically, we can split a publishing step as another job from a matrix job.

```yaml
name: 'GitHub Pages'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.build }}
    strategy:
      matrix:
        build:
          - '1'
          - '2'
          - '3'
    steps:
      - uses: actions/checkout@v2
      - run: build_stuff_into_public_dir
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public${{ matrix.build }}
          path: public
  deploy:
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts
```
