### ISSUE TITLE
Bug: Successfully pushes to branch only if it does not exist

### ISSUE THREAD

**Issue by VladimirLogachev** [peaceiris/actions-gh-pages#62]
**Describe the bug**
Successfully pushes to branch only if it does not exist yet

**To Reproduce**
1. create repo
2. deploy to `somebranch` first time (success)
3. deploy to `somebranch` second time (pipeline succeeds, but **does not actually push**)
4. delete `somebranch`
5. deploy to `somebranch` third time (success)

**Expected behavior**
Always push

**Your YAML file**
https://github.com/VladimirLogachev/vladimirlogachev.github.io
```yaml
name: Deploy to GitHub Pages
on:
  push:
    branches:
    - dev

jobs:
  build:
    name: Build elm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up elm
        uses: justgook/setup-elm@v1
      - name: Elm Make
        run: elm make src/Main.elm
      - name: Remove sources
        run: |
          rm -rf src
          rm -rf elm-stuff
          rm -rf .github
          rm -f .gitignore
          rm -f README.md
          rm -f elm.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: somebranch
          PUBLISH_DIR: .
        with:
          emptyCommits: false
```

**Comment by peaceiris** [comment]
Do you understand that `emptyCommits: false` does not push always?

And,
Is your publishing file `index.html`? Try the following.

```yaml
      - name: Prepare public
        run: |
          mkdir ./public
          mv ./index.html ./public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: somebranch
          PUBLISH_DIR: ./public
```
