### ISSUE TITLE
support: built assets not available in action

### ISSUE THREAD

**Issue by redonkulus** [peaceiris/actions-gh-pages#638]
### Checklist

- [X] I am using the latest version of this aciton.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

The issue I am seeing is that the assets that I built in the step before are not present in this action. I saw in the readme examples that building assets from other steps should be present for the action to deploy. Am I mis-configuring something in my project?

You can see in the output below that the copy command fails after the fresh clone. Ideally, the assets I build in the previous step would be available so that I can deploy them to the gh-pages branch.

### Relevant links

```markdown
Public repository: https://github.com/yahoo/react-stickynode
YAML config: https://github.com/yahoo/react-stickynode/blob/c964f69ae5c4fc4508162e5b5d987b68ea959248/.github/workflows/test.yml
YAML workflow: https://github.com/yahoo/react-stickynode/runs/3256823316?check_suite_focus=true
```

### Relevant log output

```
Prepare publishing assets
  [INFO] ForceOrphan: false
  /usr/bin/git clone --depth=1 --single-branch --branch gh-pages git@github.com:yahoo/react-stickynode.git /home/runner/actions_github_pages_1628200325080
  Cloning into '/home/runner/actions_github_pages_1628200325080'...
  Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
  [INFO] Keep existing files
  [INFO] chdir /home/runner/actions_github_pages_1628200325080
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/react-stickynode/react-stickynode/tests/functional/dist to /home/runner/actions_github_pages_1628200325080/dist/
  cp: no such file or directory: /home/runner/work/react-stickynode/react-stickynode/tests/functional/dist/.*
  [INFO] delete excluded assets
```

### Additional context.

I've tried to setup my project where the `destination_dir` is customized based on environment variables, my configuration looks like:

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3.8.0
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    destination_dir: ./dist/${{ env.GITHUB_WORKFLOW }}/${{ env.GITHUB_JOB }}/${{ env.GITHUB_RUN_NUMBER }}
    publish_dir: ./tests/functional/dist
```

In the [build](https://github.com/yahoo/react-stickynode/runs/3256823316?check_suite_focus=true) output, the destination is empty:

```
  [INFO] PublishBranch: gh-pages
  [INFO] PublishDir: ./tests/functional/dist
  [INFO] DestinationDir: ./dist///
```

It's possible I'm messing up the yaml syntax, but I've tried so many other options. I wasn't sure if the action was cleaning this some how.

**Comment by peaceiris** [comment]
### YAML

```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "${{ env.GITHUB_WORKFLOW }}/${{ env.GITHUB_JOB }}/${{ env.GITHUB_RUN_NUMBER }}"
```

### Outputs

```
//
```

**Comment by redonkulus** [comment]
@peaceiris so I know in github actions when you execute in the "run" command, you can just use `${GITHUB_WORKFLOW}` since the OS will replace the tokens, but when its in the other properties, I believe you have to use the `${{ env.FOO }}` syntax.

**Comment by peaceiris** [comment]
The [`env` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context) does not have the shell environments.

### YAML

```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set envs
        run: |
          echo "GH_WORKFLOW=${GITHUB_WORKFLOW}" >> ${GITHUB_ENV}
          echo "GH_JOB=${GITHUB_JOB}" >> ${GITHUB_ENV}
          echo "GH_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: Run a one-line script
        run: echo "${{ env.GH_WORKFLOW }}/${{ env.GH_JOB }}/${{ env.GH_RUN_NUMBER }}"
```

### Outputs

```txt
CI/build/2
```

**Comment by redonkulus** [comment]
Oh ok, will try that. Thanks!

As for my other question about the built assets, am I doing something wrong?

**Comment by redonkulus** [comment]
I tried to conform your example to the action but its still not working for me:

```
            - name: Set envs
              run: |
                  echo "GH_WORKFLOW=${GITHUB_WORKFLOW}" >> ${GITHUB_ENV}
                  echo "GH_JOB=${GITHUB_JOB}" >> ${GITHUB_ENV}
                  echo "GH_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.8.0
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  destination_dir: ./dist/${GITHUB_WORKFLOW}/${GITHUB_JOB}/${GITHUB_RUN_NUMBER}
                  keep_files: true
                  publish_dir: ./tests/functional/dist
```

I also tried `${{ env.GITHUB_WORKFLOW}}` but that was empty too.
