### ISSUE TITLE
support: No such file or directory when copying to publish assets

### ISSUE THREAD

**Issue by JoeTessier** [peaceiris/actions-gh-pages#647]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Hi, 
I'm trying to deploy a Hugo-based website, and via the GitHub actions, I run into an error saying the source folder from which to copy the resources is non existing (although it is).

I am aware of the issue #644, and even if I remove the public folder (source of the copy command in which all my resources to publish are located) just before the hugo run cmd, i've got the error as "no .../.../public folder found".

Hugo version : 0.69.0

### Relevant links

```markdown
Public repository: Private repo, confidentiality matters. Thank you for your understanding
YAML config: -
YAML workflow: -
```

### Relevant log output

[INFO] prepare publishing assets
[INFO] copy /home/runner/work/<repo-name>/<repo-name>/public to /home/runner/actions_github_pages_1630163722716
  cp: no such file or directory: /home/runner/work/<repo-name>/<repo-name>/public/.*
  [INFO] delete excluded assets
  rm: no paths given

### Additional context.

Yaml workflow : 
```yml
name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.0"

      - name: Build
        run: hugo --minify && cd public && pwd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
```

The `run: hugo --minify && cd public && pwd` cmd asserts that this folder is existing : 
```sh
Run hugo --minify && cd public && pwd
Building sites … 
                   | EN  
-------------------+-----
  Pages            | 12  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 30  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 87 ms
/home/runner/work/<repo-name>/<repo-name>/public
```

Therefore I have an empty commit, a pretty 404 on the github page, and the deploy workflow is showing a success status. 
No documentation i've tried to find regarding either GitHub actions or actions-gh-pages@v3 are mentioning such issue. 

### Second attempt
I change the content of a file (the main file, which should go into the index/html once compiled), but there's still nothing online.
```sh
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/<repo-name>/<repo-name>/public to /home/runner/actions_github_pages_1630171084498
  cp: no such file or directory: /home/runner/work/<repo-name>/<repo-name>/public/.*
  [INFO] delete excluded assets
  rm: no paths given
  [INFO] Created /home/runner/actions_github_pages_1630171084498/.nojekyll
Setup Git config
Create a commit
  /usr/bin/git commit -m deploy: 2739b6dbf6f6dfaebd1fcac775a3849183c9a8db
  [gh-pages f3ad167] deploy: 2739b6dbf6f6dfaebd1fcac775a3849183c9a8db
   1 file changed, 1 insertion(+), 1 deletion(-)
Push the commit or tag
  /usr/bin/git push origin gh-pages
  To https://github.com/<user>/<repo-name>.git
     13aa0af..f3ad167  gh-pages -> gh-pages
[INFO] Action successfully completed
```

I don't understand...

Please can you help ?
Thanks and regards
