### ISSUE TITLE
Support: issues when trying to push to external repo from PR

### ISSUE THREAD

**Issue by Kakadu** [peaceiris/actions-gh-pages#649]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Let's imagine I want to write a workflow which
1) will be called in every PR (from any possible user)
2) will push some stuff (generated documentation, linter results) to external repo

Do I understand right, that:
1) using Github Secrets is not an option, because they are not visible in PRs?
2) using access token is not an option, because it should be configured for every user that created a PR
3) using public/private key should work. I should store private key in repo and use it as 'deploy_key' in your action parameters? If yes, can I specify a key directly as local file, without exporting it to the environment (which leads to issues with escaping)?

### Relevant links

```markdown
Public repository: https://github.com/fp2021-helper/fp2021
YAML config: https://github.com/fp2021-helper/fp2021/blob/master/.github/workflows/PR.yml
YAML workflow: https://github.com/Kakadu/fp2021/pull/2/checks?check_run_id=3462642683
```

### Relevant log output

no

### Additional context.

no

**Comment by peaceiris** [comment]
Please follow the instruction correctly.

- https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-ssh-private-key-deploy_key
- https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    publish_dir: ./public
```

**Comment by Kakadu** [comment]
AFAIR my issue is solved. When I test pull-requests myself everything worked fine, but when external contributor tries to pull-request, he/she doesn't have access to deploy keys. The solution is to split workflow in two and pass generated artifact to second one, which has access to deploy keys and other permissions.

**Comment by peaceiris** [comment]
We can control a job/step execution with the filter `if: ${{ github.ref == 'refs/heads/main' }}`. See the latest workflow examples on the README.md of this repository and the GitHub Actions official docs for more details.

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      ...
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
