### ISSUE TITLE
Proposal: Add option to define custom Git user.name and user.email

### ISSUE THREAD

**Issue by orzyyyy** [peaceiris/actions-gh-pages#66]
**Describe the bug**
I want to change the user.name and user.email, such as 'test-user' and 'test-user@gmail.com' for deploy commits.

**Expected behavior**
Assume this is the commit list:

```bash
Commits on Dec 24, 2019
  chore: deploy to gh-pages      
  `orzyyyy` committed 17 minutes ago
      |
      ---------------------->   this one is not the expected user
```
---

```bash
Commits on Dec 24, 2019
  chore: deploy to gh-pages                        
    `test-user` committed 17 minutes ago
      |
      ---------------------->   this one is expected
```

**Your YAML file**
```yaml
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set username and email
        run: |
          git config --global user.name "test-user"
          git config --global user.email test-user@gmail.com

      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: debug
        run: git config --list

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false

```
