### ISSUE TITLE
support: Using personal_token to push to an external repo is failing due to missing fetch

### ISSUE THREAD

**Issue by vhsantos26** [peaceiris/actions-gh-pages#667]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Currently, we are using the action to push the Allure Report using our code repo but we are moving to an external repository and, during the changes, we faced the git error due to an updated repository but we just clone it and push the page.

_NOTE: All repositories are private._

### Relevant links

```markdown
Private repository
```

### Relevant log output

```
  /usr/bin/git push origin quality-report-pages
  To https://github.com/ALJAZEERAPLUS/test-reports.git
   ! [rejected]        quality-report-pages -> quality-report-pages (fetch first)
  error: failed to push some refs to '***github.com/ALJAZEERAPLUS/test-reports.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

### Additional context.

Here are an example how we are using on the CI/CD

```
  e2e_tests_android_report_test:
    runs-on: [self-hosted, linux, mobile]
    environment:
      name: allure
      url: ${{ steps.get_job_url.outputs.url_output }}
    needs: e2e_tests_android_test
    steps:
      - name: Get Allure History
        uses: actions/checkout@v2.3.5
        with:
          repository: ALJAZEERAPLUS/test-reports
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: e2e-android-result
          path: output/report

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: output/report
          allure_report: mobile/${{ env.BRANCH_NAME }}/android
          gh_pages: quality-report-pages
          allure_history: output/report/allure-history
          subfolder: mobile/${{ env.BRANCH_NAME }}/android
          github_repo: ALJAZEERAPLUS/test-reports

      - name: Deploy Allure Report to Github Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: ALJAZEERAPLUS/test-reports
          publish_branch: quality-report-pages
          publish_dir: mobile/${{ env.BRANCH_NAME }}/android
          destination_dir: mobile/${{ env.BRANCH_NAME }}/android
```
