### ISSUE TITLE
support: cp: no such file or directory

### ISSUE THREAD

**Issue by Aloento** [peaceiris/actions-gh-pages#674]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

```
      - run: yarn && yarn build

      - name: Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

```
  [INFO] copy /home/runner/work/Aloento/Aloento/public to /home/runner/actions_github_pages_1638395046724
  cp: no such file or directory: /home/runner/work/Aloento/Aloento/public/.*
```

### Relevant links

```markdown
Public repository: https://github.com/Aloento/Aloento
YAML workflow: https://github.com/Aloento/Aloento/blob/master/.github/workflows/hexo.yml
```

### Relevant log output

```
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/Aloento/Aloento/public to /home/runner/actions_github_pages_1638395046724
  cp: no such file or directory: /home/runner/work/Aloento/Aloento/public/.*
  [INFO] delete excluded assets
  rm: no paths given
```

### Additional context.

I'm sure my `/home/runner/work/Aloento/Aloento/public` exists and has my files.
