### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by zeyadetman** [peaceiris/actions-gh-pages#68]
**Describe the bug**
I got this problem while deploying Gatsbyjs project to github pages.

> Load key "/root/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
##[error]Docker run failed with exit code 128

**To Reproduce**
Here's How I created the .yml file

```
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn
    - run: git config --global user.email "zeyadetman@gmail.com"
    - run: git config --global user.name "Zeyad Etman"
    
    - run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_API_DEPLOY }}
        PERSONAL_TOKEN: ${{ secrets.GITHUB_API_DEPLOY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
```

**Expected behavior**
It deploys successfully.

**Additional context**
I'm building with yarn.

**Comment by peaceiris** [comment]
Read the docs carefully.

> Go to Deploy Keys and add your public key with the Allow write access.

**Comment by peaceiris** [comment]
And, if we use `ACTIONS_DEPLOY_KEY`, we do not need `PERSONAL_TOKEN`.

**Comment by peaceiris** [comment]
Do you understand `ACTIONS_DEPLOY_KEY` is for the ssh protocol?

**Comment by peaceiris** [comment]
Also, this repository provides [an example workflow for Gatsby project](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-gatsby).

**Comment by peaceiris** [comment]
We can [set a custom Git user.name and user.email.](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-git-username-and-email)

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v2
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
  with:
    username: "iris"
    useremail: "iris@peaceiris.com"
```
