### ISSUE TITLE
Adding peaceiris/actions-gh-pages@v2 to action with PUBLISH_BRANCH: master  and PUBLISH_DIR: .  causes it to self-delete each time it runs

### ISSUE THREAD

**Issue by bw2** [peaceiris/actions-gh-pages#69]
Adding 
```
   - name: Deploy	
      uses: peaceiris/actions-gh-pages@v2	
      env:	
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}	
        #PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}	
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
        PUBLISH_BRANCH: master	
        PUBLISH_DIR: .
```
to the end of a workflow causes it to delete the workflow file from github each time it runs: 
https://github.com/macarthur-lab/omim-search/commit/b83f911f646ad510689aae2f091ca2dfc0b3d590
Example run logs are here:
https://github.com/macarthur-lab/omim-search/runs/366450678

**Comment by peaceiris** [comment]
Do you understand the GitHub Pages spec? If you use the master branch to manage your source contents, the `gh-pages` branch should be used as a GitHub Pages branch.

Therefore, you should change as follows.

```diff
- PUBLISH_BRANCH: master
+ PUBLISH_BRANCH: gh-pages
```

And, `PUBLISH_DIR: .` is not recommended. You do not need to deploy the `.py` files, it is better to create a new directory and put your deploy assets into the directory. Then, set `PUBLISH_DIR: ./public`.

cf. https://github.com/peaceiris/actions-gh-pages/issues/62#issuecomment-568304605

```yaml
      - name: Prepare public
        run: |
          mkdir ./public
          mv ./index.html ./favicon.ico ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
```

**Comment by bw2** [comment]
Just pointing out the unexpected behavior when non-default settings are used for github pages.

**Comment by peaceiris** [comment]
Thank you. The non-default settings are already mentioned by our README. Read the docs carefully.

> [actions-gh-pages/README.md at master · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/blob/master/README.md#%EF%B8%8F-repository-type---user-and-organization)

```yaml
on:
  push:
    branches:
    - source  # default branch

PUBLISH_BRANCH: master  # deploying branch
```

https://github.com/peaceiris/actions-gh-pages/blob/0252bbee4ddab91da948416bd5d300a7baf47216/README.md#L178-L197
