### ISSUE TITLE
support: Jekyll step runs, even with `.nojekyll` file

### ISSUE THREAD

**Issue by Tycholiz** [peaceiris/actions-gh-pages#694]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

As described in [this post](https://github.com/peaceiris/actions-gh-pages/pull/438), `.nojekyll` file is being generated automatically. However, for some reason the Jekyll step is still being run, even though I have a Next.js site.

Here is my workflow file:
```yml
name: Dendron

on:
  push:
    branches:
    - auto-deploy-digital-garden

  ## every day at midnight
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-nextjs-site:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Dendron (main) repo
      uses: actions/checkout@v2
      with:
        repository: Tycholiz/Dendron
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        path: 'main'

    - name: Clone Dendron (publishable) repo
      uses: actions/checkout@v2
      with:
        path: 'publishable'
        ref: master
        fetch-depth: 0

    - name: Delete publishable cached files if present
      run: "rm -rf .next && rm -rf docs && rm -rf node_modules"
      working-directory: ./publishable

    - name: Install npm dependencies of publishable
      run: npm install @dendronhq/dendron-cli@latest
      working-directory: ./publishable

    - name: Clone the Dendron Next.js repository and install dependencies
      run: npx dendron publish init --wsRoot .
      working-directory: ./publishable

    - name: Build static HTML and create the Nextjs static website
      run: npx dendron publish export --target github --yes --wsRoot .
      working-directory: ./publishable

    - name: 🚀 Deploy site to GH Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: publishable # deploy publishable/docs directory to pages branch
        force_orphan: true
        enable_jekyll: false
        cname: "tycholiz.github.io"
```

And I linked the `pages` branch of my repo below. As you can see, I have the `.nojekyll` file, yet for some reason that Build page with Jekyll step keeps running. 

Am I missing something obvious here?

### Relevant links

[Public repository](https://github.com/Tycholiz/Digital-Garden/tree/pages)
[YAML workflow](https://github.com/Tycholiz/Digital-Garden/runs/4830916462?check_suite_focus=true)

### Relevant log output

Build page with Jekyll step
```
Run actions/jekyll-build-pages@v1-beta
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1beta_f8fa0f --label 9916a7 --workdir /github/workspace --rm -e INPUT_SOURCE -e INPUT_DESTINATION -e INPUT_FUTURE -e INPUT_BUILD_REVISION -e INPUT_VERBOSE -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e ACTIONS_ID_TOKEN_REQUEST_URL -e ACTIONS_ID_TOKEN_REQUEST_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Digital-Garden/Digital-Garden":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1-beta
Configuration file: none
  Logging at level: debug
      GitHub Pages: github-pages v223
      GitHub Pages: jekyll v3.9.0
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs
/usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:86:in `chdir': No such file or directory @ dir_chdir - /github/workspace/docs (Errno::ENOENT)
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:86:in `sass_load_paths'
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:114:in `sass_configs'
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:101:in `block in convert'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `reduce'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `convert'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:83:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-223/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-223/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /github/workspace/./docs
       Destination: /github/workspace/./docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
        Generating: JekyllOptionalFrontMatter::Generator finished in 1.23e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 6.2e-06 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 3.5e-06 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 3.04e-05 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 1.34e-05 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 7.801e-06 seconds.
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
github-pages 223 | Error:  No such file or directory @ dir_chdir - /github/workspace/docs
```
