### ISSUE TITLE
proposal: Allow configuration of Git's `user.email` and `user.name`

### ISSUE THREAD

**Issue by jaredsburrows** [peaceiris/actions-gh-pages#714]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Using custom build scripts, I can set the `user.email` and `user.name`, see here(https://github.com/jaredsburrows/cs-interview-questions/commit/730f0223cda6fd8a7ffa01853aab525a73beb66f):
```
git config --global user.email "action@github.com"
git config --global user.name "Github Actions"
git clone --quiet https://${GH_TOKEN}@github.com/${SLUG} temp-clone &> /dev/null
```

### Describe the solution you'd like

```
      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/docs/asciidoc
          userEmail: "action@github.com"
          userName: "Github Actions"
```

### Additional context

Now I am seeing the following:
<img width="1350" alt="Screen Shot 2022-02-25 at 7 41 42 PM" src="https://user-images.githubusercontent.com/1739848/155821263-10eaf18a-623b-48dc-b85d-aa02f84d6c89.png">

**Comment by jaredsburrows** [comment]
Figured it out:
```
      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/docs/asciidoc
          user_name: "Github Actions"
          user_email: "action@github.com"

```

Reference:
 - https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-git-username-and-email
