### ISSUE TITLE
proposal: auto-retry

### ISSUE THREAD

**Issue by vallyian** [peaceiris/actions-gh-pages#759]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Action fails intermitently due to concurrent updates

![image](https://user-images.githubusercontent.com/26962998/172606202-81d17467-8f39-45e5-a495-0df90d82d9cf.png)

### Describe the solution you'd like

Action should implement/support an auto retry mechanism e.g. `retry: 3`

### Describe alternatives you've considered

Two consecutive steps for publishing where the second one only runs if the first one fails

**Comment by peaceiris** [comment]
I think the `concurrency.group` already resolves this instead.

```yaml
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
```

**Comment by peaceiris** [comment]
The current example workflow on README includes the approach already.
Please try the `concurrency.group` first.

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
