### ISSUE TITLE
proposal: Create Tag on Commit

### ISSUE THREAD

**Issue by cinderblock** [peaceiris/actions-gh-pages#76]
**Is your feature request related to a problem? Please describe.**
I'd like to tag specific versions of my `gh-pages` branch programmatically (in my case, based on `package.json` version)

**Describe the solution you'd like**
I'd like an option to add a tag with a specified name on commit.

**Describe alternatives you've considered**
Manually - PITA.

**Additional context**
I'm thinking I'd like to be able to use this like so:

```yml
- name: Tagged Deploy
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
    CREATE_TAG: ${{ <expression> }}
```

Where expression might load some values from other steps or combine readily available job information.

Other options for forcing the overwrite of an existing tag or not might make sense too.

**Comment by peaceiris** [comment]
It sounds interesting. I will consider that option this weekend. (I'm busy now.)

**Comment by peaceiris** [comment]
My suggestion.

```yaml
- name: Prepare deployment
  id: prepare_deployment
  run: |
    TAG_NAME="v$(jq -r '.version' ./package.json)"
    echo "::set-output name=tag_name::${TAG_NAME}"

- name: Tagged Deploy
  uses: peaceiris/actions-gh-pages@v2
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
  with:
    tagName: ${{ steps.prepare_deployment.outputs.tag_name }}
```

> Other options for forcing the overwrite of an existing tag or not might make sense too.

Yes.
