### ISSUE TITLE
proposal: keep_history option

### ISSUE THREAD

**Issue by Shigma** [peaceiris/actions-gh-pages#77]
**Is your feature request related to a problem? Please describe.**
I'm migrating my pages from travis which provides a `keep_history` option. If set to `false`, the building process will only preserve the last commit to the target branch. So I would love to have a similar option here.

**Describe the solution you'd like**
A `keep_history` option, default to `true`.

**Describe alternatives you've considered**
A `remove_history` option, default to `false`.

**Additional context**
N/A

**Comment by peaceiris** [comment]
Do you mean the `forceOrphan` option?

> we can set the `forceOrphan: true` option. This allows you to make your publish branch with only the latest commit.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v2
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
  with:
    forceOrphan: true
```
