### ISSUE TITLE
proposal: Deploy to subdirectory?

### ISSUE THREAD

**Issue by bcjordan** [peaceiris/actions-gh-pages#79]
**Is your feature request related to a problem? Please describe.**

I would like to deploy each branch's page to its own gh-pages sub-folder, for e.g. feature branch pages

**Describe the solution you'd like**

A parameter TARGET_FOLDER that allows me to specify a sub-folder for the build

**Describe alternatives you've considered**

https://github.com/marketplace/actions/deploy-to-github-pages supports this

**Comment by peaceiris** [comment]
We can already deploy subdirectories to a publish branch using the `keepFiles` option.

```yaml
- name: Setup assets
  run: |
    mkdir public subdir1
    mv your_contents ./subdir1/
    mv ./subdir1 ./public/

- name: Deploy
  uses: peaceiris/actions-gh-pages@v2
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
  with:
    keepFiles: true
```
