### ISSUE TITLE
support: How to publish multiple directories using single action ?

### ISSUE THREAD

**Issue by sriramkukkadapu** [peaceiris/actions-gh-pages#797]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

For Ex: I have 2 folders
output
output2
i want these 2 folders should be published as artifacts separately in single action.

How to achieve this ?

### Relevant links

```markdown
Public repository:
YAML config:
YAML workflow:
```

**Comment by peaceiris** [comment]
We can just move several folders into the public folder.

```yaml
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ...

      - name: Create public
        run: |
          mkdir ./public
          cp -r output1 output2 ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
