### ISSUE TITLE
Bug: Run failed.  [error]File not found

### ISSUE THREAD

**Issue by Hyuuko** [peaceiris/actions-gh-pages#88]
**Describe the bug**

Run failed with peaceiris/actions-gh-pages@v3

**To Reproduce**

my yml file:
```yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book
          force_orphan: true
```

error:
```
Run peaceiris/actions-gh-pages@v3
  with:
    personal_token: ***
    publish_branch: gh-pages
    publish_dir: ./book
    force_orphan: true
    allow_empty_commit: false
    keep_files: false
##[error]File not found: '/home/runner/work/_actions/peaceiris/actions-gh-pages/v3/lib/index.js'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44204137/73841968-a6bccd80-4856-11ea-8704-71d2de7d648d.png)
