### ISSUE TITLE
About limitation of GITHUB_TOKEN

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#9]
GitHub Actions v2 is still beta and deploying to GitHub Pages with `GITHUB_TOKEN` has some problems. Until it is fixed, I provide `ACTIONS_DEPLOY_KEY` to deploy with ssh from `peaceiris/actions-gh-pages@v2.0.0`

**Comment by hakusaro** [comment]
Does this cause the `fatal: could not read Username for 'https://github.com': No such device or address` error?

**Comment by peaceiris** [comment]
No, your case seems to be new. Please create a new issue and tell me more details.

**Comment by thefringeninja** [comment]
I ran into the same issue. The manual way to fix it is from settings, flip your branch to `master` and then back to `gh-pages`.

A better way to fix it is to create a personal access token and use that in secrets instead.

**Comment by peaceiris** [comment]
Thanks @thefringeninja 
I will release `v2.0.0` soon. It supports `GITHUB_TOKEN` and `ACTIONS_DEPLOY_KEY`. `ACTIONS_DEPLOY_KEY` is for deploying with ssh.

> A better way to fix it is to create a personal access token and use that in secrets instead.

We will be able to set a personal access token as `ACTIONS_DEPLOY_KEY`

**Comment by peaceiris** [comment]
`v2.0.0` is released.

**Comment by nicolas-van** [comment]
@peaceiris : Do you know if there is a support ticket for this problem ?

**Comment by peaceiris** [comment]
This problem is a known issue. I have faced the same issue on GitHub Actions v1. Thus, some people have reported this to GitHub support. As you see at the https://github.com/JamesIves/github-pages-deploy-action/issues/5, GitHub should already know this. If this issue is not fixed for a long time, we probably 
should report this in the [GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions) as well.

**Comment by peaceiris** [comment]
I found the post on the GitHub Community Forum.

[Github action not triggering gh-pages upon push - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869)

Community Manager said:

> The `GITHUB_TOKEN` that is provided as a part of GitHub Actions doesn't have authorization to create any successive events, such as GitHub Pages builds. So while you can push to the `gh-pages` branch using the `GITHUB_TOKEN`, it won't spawn a GitHub Pages build. You'll need to create a personal access token and supply it to your GitHub Action as a secret.

**Comment by nicolas-van** [comment]
Yes, it seems like that's not a bug but a normal behavior in the context of the security rule imposed in Github Actions which is "A workflow can not trigger another workflow".

I posted an answer to ask if they could re-consider this limitation in this precise use case due to the obvious usability issue it creates. I propose that we wait their answer and if it's negative we could just close this issue as "not a bug" and adapt the documentation of this project to explain it will never be possible to use `GITHUB_TOKEN`.

**Comment by peaceiris** [comment]
Thank you @nicolas-van 

> Yes, it seems like that's not a bug but a normal behavior in the context of the security rule imposed in Github Actions which is "A workflow can not trigger another workflow".

I got it clearly. I will update the README following your suggestion.

**Comment by nicolas-van** [comment]
Hmmm, according to the most recent answer of [this thread](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869) it might not be by design in the end. I'm gonna test what is proposed to see if it works when I have some time.

**Comment by peaceiris** [comment]
Yes, I am also following that thread.

> Here's an example that should work:

```
# pushes using the user that kicked off the action. Requires `jq` in the builder
git config user.name $(jq .pusher.username $GITHUB_PAYLOAD)
git config user.email $(jq .pusher.email $GITHUB_PAYLOAD)

git add --all
git commit -m "Publish to gh-pages branch"
git remote add pages https://x-access-token:$GITHUB_TOKEN@github.com/:owner/:repo.git
git push pages gh-pages -f
```

This action already supports the above and I tested at [peaceiris/hugo-test-project]. I could push to `gh-pages` branch using `GITHUB_TOKEN` but GitHub Pages building did not start.

[peaceiris/hugo-test-project]: https://github.com/peaceiris/hugo-test-project/commit/47bd7cf05eb59aeaca809361792d6c5464e9afd3/checks

**Comment by peaceiris** [comment]
I found it. The following step will work well.

```yaml
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.4.0/entrypoint.sh
        bash ./entrypoint.sh
```

**Comment by peaceiris** [comment]
No, some repository faild.

**Comment by NGTmeaty** [comment]
I have a private repo setup and GITHUB_TOKEN still isn't working. I see someone else above had the same issue as me: https://github.com/peaceiris/actions-gh-pages/issues/13 but he just moved to a deploy key. Do we know if there's a actual solution to that above?

**Comment by peaceiris** [comment]
This problem is about permissions of the default token between GitHub Pages and GitHub Actions. GitHub team is investigating it and we are waiting for a good reply from them. Currently, there is no actual solution.

- [Github action not triggering gh-pages upon push - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869)

**Comment by NGTmeaty** [comment]
I was using the PERSONAL_TOKEN env variable and passing in a GITHUB_TOKEN, oops :) Switching that to a GITHUB_TOKEN env variable with a GITHUB_TOKEN, everything worked perfectly :) Thanks!

**Comment by mikeal** [comment]
I had a chat with someone at GitHub today about this very issue (calling Actions from other Actions) and found out that, while GitHub Actions won’t trigger push events for other actions, they do trigger repo events, so if you listen for a repo event instead of a the push event you avoid this issue.

**Comment by peaceiris** [comment]
Thank you @mikeal 

Do you mean that the default `GITHUB_TOKEN` does not have permission for repo events on a public repository? I think the token has repo events access. Why cannot we trigger the GitHub Pages build event with the default `GITHUB_TOKEN` on a public repository? (On a private repository, we can do that.)

**Comment by shaunakv1** [comment]
Hello, 

In my case I am added as a collaborator (full admin access) to an Organization. I am trying to setup a simple static site push to gh-pages. I have setup using `ACTIONS_DEPLOY_KEY`. The deploy succeeds but the site changes are not reflected. In-fact if I manually delete gh-pages branch and re-run the action, it succeeds again, but the site is never published. All the code seems okay in gh-pages.  What am I doing wrong?  here' s my action yaml


```yaml
name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v1

      - name: Build
        run: |
          rm -rf dist
          rsync -rv --exclude=.git --exclude=.github . dist

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist

```
