### ISSUE TITLE
Error: EEXIST: file already exists, mkdir '/home/runner/actions_github_pages/404.html'"

### ISSUE THREAD

**Issue by indefinitus** [peaceiris/actions-gh-pages#90]
**Describe the bug**
Failed when a **folder** is named like a file, eg. `404.html`.

**To Reproduce**
Create a folder named like a flle in `public` folder.
eg.
![image](https://user-images.githubusercontent.com/18642966/73864627-f910e500-487c-11ea-8071-e9e287198732.png)

**Your YAML file**
```yml
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.0.1
      with:
        personal_token: ${{ secrets.GITHUB_PAT }}
        publish_branch: master
        publish_dir: public
        # force_orphan: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18642966/73864777-2a89b080-487d-11ea-86ea-ee7ffffce18f.png)
