### ISSUE TITLE
Bug: ##[error]File not found: '...index.js'

### ISSUE THREAD

**Issue by hamelsmu** [peaceiris/actions-gh-pages#98]
**Describe the bug**
Link to the error message: https://github.com/machine-learning-apps/actions-ml-cicd/runs/439658392?check_suite_focus=true#step:7:12

![image](https://user-images.githubusercontent.com/1483922/74284853-7606e900-4cd9-11ea-803f-f8b1d9ef5eec.png)

**To Reproduce**

```yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@master
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/_site
```

**Your YAML file**

[Link to my YAML file](https://github.com/machine-learning-apps/actions-ml-cicd/actions/runs/37815875/workflow)

cc: @awmatheson

**Comment by peaceiris** [comment]
Dupulicate of #84 

Please use the latest version v3 and read the latest README.

```yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/_site
```

A default value of `publish_branch` is `gh-pages`.
